### ISSUE TITLE
Features 

### ISSUE THREAD

**Issue by GhostBuster122** [nesrak1/UABEA#1]
Can you add plugin features please? I like to make texture pack for games but old UABE doesn't support Unity 2019.4.22

**Comment by nesrak1** [comment]
I'd like to add plugins (as the readme says) but I don't know when I'll be able to get to it since I've not had much time. But it's definitely on the todo list.

**Comment by A-nonymous027** [comment]
Finally there's someone I can put my hopes on. UABE was pretty much stagnant so I'd like to respect new coders that revives it.

**Comment by JerryPLayz** [comment]
Is there any possibility of enabling command-line access to the features in your program? It would be helpful with my project which needs explicitly to extract the contents of an emip file.

**Comment by nesrak1** [comment]
@JerryPLayz yes, command line support is something I forgot to put on the features list. I'll probably start with that since it's the easiest. I'm still working on basic features like bundle writing and asset adding/removing.

**Comment by JerryPLayz** [comment]
Would that include bundle exporting (like unzipping a .zip file?) @nesrak1

**Comment by nesrak1** [comment]
Yes

**Comment by JerryPLayz** [comment]
Hello again, can I just check that your tentative "command line support?" that it exists, or is there something that needs to be done? @nesrak1

**Comment by nesrak1** [comment]
It does exist but I haven't done much testing on it. If you decide to build the repo to try it, you'll need to build AssetsTools.NET since I had to fix some bugs there as well.

**Comment by drongood12** [comment]
Is there currently a function for adding new data to assets?

**Comment by nesrak1** [comment]
New assets to an assets file or new asset data (like entries into an array) into a single asset? Assuming you mean adding new assets you can't currently add a new asset or remove an asset from a file so far.

**Comment by drongood12** [comment]
> New assets to an assets file or new asset data (like entries into an array) into a single asset? Assuming you mean adding new assets you can't currently add a new asset or remove an asset from a file so far.
Yes, you understood me correctly, but approximately when should we expect the addition of such a function?

**Comment by nesrak1** [comment]
Whenever it gets done. There are other problems that are preventing me from implementing this right now.

**Comment by nesrak1** [comment]
@drongood12 I reworked a large portion of uabea to get reading/writing from new and modified assets (about 1500 changed lines). Because of that, I wouldn't say it's stable yet but you should be able to add and remove assets as long as you don't try to do anything crazy with it.

**Comment by drongood12** [comment]
> @drongood12 I reworked a large portion of uabea to get reading/writing from new and modified assets (about 1500 changed lines). Because of that, I wouldn't say it's stable yet but you should be able to add and remove assets as long as you don't try to do anything crazy with it.

wow, super, I will definitely test the new version today, thanks, also a little later i will create several issues, found several not so critical bugs in a couple of days of use

**Comment by drongood12** [comment]
> @drongood12 I reworked a large portion of uabea to get reading/writing from new and modified assets (about 1500 changed lines). Because of that, I wouldn't say it's stable yet but you should be able to add and remove assets as long as you don't try to do anything crazy with it.

I tried to add it to a large file, but it is not clear where the asset was added, it would not be bad if it was added to the very beginning, because it is more convenient to edit the asset and import existing assets, because I planned to create an asset and import raw into it data
![image](https://user-images.githubusercontent.com/73915636/120708220-fc919c00-c4c3-11eb-9845-93f3d520f2ce.png)

**Comment by drongood12** [comment]
Also, saving is not very convenient, in order for me to save the change, I need to save in a new bundle file, especially this is not convenient with large files, I have to save a bundle every time, which is 3 GB

**Comment by nesrak1** [comment]
> I tried to add it to a large file, but it is not clear where the asset was added, it would not be bad if it was added to the very beginning, because it is more convenient to edit the asset and import existing assets, because I planned to create an asset and import raw into it data

If you created an asset with a new pathId, then the new asset will show at the top of the list. It's possible you overwrote another asset without realizing or have the list in sorted and the sort moved the asset somewhere else. The add dialog does not warn you about overwriting right now.

> Also, saving is not very convenient, in order for me to save the change, I need to save in a new bundle file, especially this is not convenient with large files, I have to save a bundle every time, which is 3 GB

Normal UABE does this too due to the way asset loading/saving works. There's no real way around this unless you want it to close and reopen the file every time you save.
