### ISSUE TITLE
无法替换png

### ISSUE THREAD

**Issue by YZJH123456** [nesrak1/UABEA#102]
在替换制作好的图片的时候 点ok就提示 应用程序中发生了未处理的异常。如果单击继续 应用程序将忽略此错误并尝试继续 如果点击退出应用将立即关闭

有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.BadImageFormatException: 试图加载格式不正确的程序。 (0x8007000B)
   at Texture.PInvoke.EncodeByPVRTexLib(IntPtr data, IntPtr buf, Int32 mode, Int32 level, Int32 space, UInt32 width, UInt32 height)
   at Texture.TextureWrapper.EncodeByPVRTexLib(Byte[] data, Int32 mode, Int32 level, Int32 space, Int32 width, Int32 height) in C:\Users\Lenovo\source\repos\AssetsAdvancedEditor\Plugins\Texture\TextureWrapper.cs:line 40
   at Texture.TextureManager.EncodeTexture(Byte[] data, Int32 width, Int32 height, TextureFormat format, Int32 quality) in C:\Users\Lenovo\source\repos\AssetsAdvancedEditor\Plugins\Texture\TextureManager.cs:line 201
   at Texture.EditTextureDialog.btnOK_Click(Object sender, EventArgs e) in C:\Users\Lenovo\source\repos\AssetsAdvancedEditor\Plugins\Texture\EditTextureDialog.cs:line 86
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
System.Private.CoreLib
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Private.CoreLib.dll
----------------------------------------
AssetsAdvancedEditor
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///C:/Users/Administrator/Desktop/UAAE/AssetsAdvancedEditor.dll
----------------------------------------
System.Runtime
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    程序集版本:5.0.9.0
    Win32 版本:5.0.921.36302
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.9/System.Windows.Forms.dll
----------------------------------------
System.Windows.Forms.Primitives
    程序集版本:5.0.9.0
    Win32 版本:5.0.921.36302
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.9/System.Windows.Forms.Primitives.dll
----------------------------------------
System.ComponentModel.Primitives
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.ComponentModel.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Collections.Specialized.dll
----------------------------------------
System.Console
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Console.dll
----------------------------------------
System.Drawing.Common
    程序集版本:5.0.0.2
    Win32 版本:5.0.421.11614
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.9/System.Drawing.Common.dll
----------------------------------------
System.Threading
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Collections.dll
----------------------------------------
AssetsTools.NET
    程序集版本:2.0.0.0
    Win32 版本:2.0.0.0
    基本代码:file:///C:/Users/Administrator/Desktop/UAAE/AssetsTools.NET.dll
----------------------------------------
netstandard
    程序集版本:2.1.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/netstandard.dll
----------------------------------------
Microsoft.Win32.Primitives
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Threading.Thread.dll
----------------------------------------
Accessibility
    程序集版本:4.0.0.0
    Win32 版本:5.0.921.36302
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.9/Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.ComponentModel.TypeConverter.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    程序集版本:5.0.0.0
    Win32 版本:5.0.20.51904
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.9/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Collections.Concurrent
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Collections.Concurrent.dll
----------------------------------------
System.Runtime.Extensions
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Runtime.Extensions.dll
----------------------------------------
System.ComponentModel
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.ComponentModel.dll
----------------------------------------
System.Memory
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Memory.dll
----------------------------------------
System.Buffers
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Buffers.dll
----------------------------------------
System.Resources.Extensions
    程序集版本:5.0.0.0
    Win32 版本:5.0.20.51904
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.9/System.Resources.Extensions.dll
----------------------------------------
System.ObjectModel
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.ObjectModel.dll
----------------------------------------
System.Linq
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Linq.dll
----------------------------------------
System.Collections.NonGeneric
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Collections.NonGeneric.dll
----------------------------------------
System.IO.FileSystem
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.IO.FileSystem.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.Text.RegularExpressions
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Text.RegularExpressions.dll
----------------------------------------
Mono.Cecil
    程序集版本:0.11.3.0
    Win32 版本:0.11.3.0
    基本代码:file:///C:/Users/Administrator/Desktop/UAAE/Mono.Cecil.dll
----------------------------------------
Texture
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///C:/Users/Administrator/Desktop/UAAE/Plugins/Texture.dll
----------------------------------------
System.Drawing
    程序集版本:5.0.9.0
    Win32 版本:5.0.921.36302
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.9/System.Drawing.dll
----------------------------------------
System.Private.Uri
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Private.Uri.dll
----------------------------------------
SixLabors.ImageSharp
    程序集版本:1.0.0.0
    Win32 版本:1.0.3.0
    基本代码:file:///C:/Users/Administrator/Desktop/UAAE/SixLabors.ImageSharp.dll
----------------------------------------
System.Numerics.Vectors
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Numerics.Vectors.dll
----------------------------------------
System.Runtime.Intrinsics
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Runtime.Intrinsics.dll
----------------------------------------
System.IO.Compression
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.IO.Compression.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:5.0.9.0
    Win32 版本:5.0.921.36302
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.9/zh-Hans/System.Windows.Forms.resources.dll
----------------------------------------
System.Diagnostics.StackTrace
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Collections.Immutable.dll
----------------------------------------
System.Text.Encoding.Extensions
    程序集版本:5.0.0.0
    Win32 版本:5.0.921.35908
    基本代码:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Text.Encoding.Extensions.dll
----------------------------------------

************** JIT 调试 **************

**Comment by nesrak1** [comment]
> AssetsAdvancedEditor
You may want to take this up with the fork-thats-pretending-not-to-be-a-fork UAAE.
In any case, could you potentially be on a 32bit windows? This program is only compiled for 64bit.

**Comment by YZJH123456** [comment]
那现在AssetsBundleExtractor没办法对捆绑文件进行替换 那该用啥  还有啥能对32位的进行替换的软件呢

**Comment by nesrak1** [comment]
I can build a 32 bit version later, but I have no guarantee it will work.

**Comment by YZJH123456** [comment]
好的,非常感谢

**Comment by YZJH123456** [comment]
期待你的32版本

**Comment by nesrak1** [comment]
Here is a 32 bit build.
[net5.0.zip](https://github.com/nesrak1/UABEA/files/7123941/net5.0.zip)

I won't set this up with the build bot, but if you need updates in the future you can just build the repo from source after changing the build platform to x86 and it should work out of the box.
