### ISSUE TITLE
App not installed issue

### ISSUE THREAD

**Issue by snowcatgp** [nesrak1/UABEA#104]
So basically, when I finish editing this game's: https://subway-surfers.en.uptodown.com/android/download
files and save them, the apk file looks fine, and opens normally in package installer, but once I click "install" it gives the "App not Installed" error message, I'd really appreciate your help and thank you.

**Comment by nesrak1** [comment]
This is not a uabea issue. You probably didn't sign your apk.

**Comment by snowcatgp** [comment]
> This is not a uabea issue. You probably didn't sign your apk.

I tried signing it but it didn't work, do you know any good signing programs/apps?

**Comment by nesrak1** [comment]
You probably need to uninstall the original since the signature is different. But again this isn't the best place to ask android questions.

**Comment by snowcatgp** [comment]
> You probably need to uninstall the original since the signature is different. But again this isn't the best place to ask android questions.

I figured it out, thank you so much.
