### ISSUE TITLE
Program doesn't do anything on launch

### ISSUE THREAD

**Issue by eeveeishpowered** [nesrak1/UABEA#11]
Program doesn't do anything when launched/ran. Doesn't even flash on screen for a second before closing immediately after.
I would love to provide logs but it seems no logs are created. Guess I'm sticking to the normal UABE for now.

**Comment by nesrak1** [comment]
Yeah that's not too much to go off of. Just a few questions:
* what os are you running?
* have you made sure you're not running from inside the zip?
* do you have .net 5 installed (I think if you don't have it installed it makes a popup asking to install it though)
Anyway, this project is still very much a wip so if you can use the original UABE (don't need newer unity versions), you probably should use that for now.

**Comment by eeveeishpowered** [comment]
Installing the .NET 5.0 SDK fixed it, will be closing this issue
