### ISSUE TITLE
Crash when opening sharedassets.resource file or when opening sharedassets.split0 without merge

### ISSUE THREAD

**Issue by Halal-Dev** [nesrak1/UABEA#110]
I get crash when opening sharedassets.resource file or when opening sharedassets.split0 files of granny 3.
Or could someone tell me if it would work if i merge all splits and put it in game files ?

**Comment by nesrak1** [comment]
> I get crash when opening sharedassets.resource file

That's not an assets file, that's usually raw data like .resS files.

> or when opening sharedassets.split0 files of granny 3.

Are you choosing to merge the files when you open them? Or does that option not show open?

**Comment by Halal-Dev** [comment]
> > I get crash when opening sharedassets.resource file
> 
> That's not an assets file, that's usually raw data like .resS files.
> 
> > or when opening sharedassets.split0 files of granny 3.
> 
> Are you choosing to merge the files when you open them? Or does that option not show open?

It does show, and when i press merge it works right, but problem is that i dont know if the game would work if i replace split files with the merged one
