### ISSUE TITLE
\n and \r escaping on text asset dump importing

### ISSUE THREAD

**Issue by galaipa** [nesrak1/UABEA#114]
Hello,
I'm having some trouble when trying to escape the new line sequence (\n) using the "Import dump" tool, and I suspect that it might a be bug or a limitation of the program. 

When I export the text asset of the AmongUs videogame, the resulting dump looks like this:
```quote
\r\nHowToPlayText42       Firstly, determine who you want to play with!\\n\\nIf you want to play with friends online
```
As the text shows, the different translation string records are separated with `\r\n`. That works nicely, but the problem comes when some strings include `\\n` (like in the example above). According to what I tried (but I might we wrong), there is no way to export those espaced line breaks `\\n` back to the asset file. The program [converts them](https://github.com/nesrak1/UABEA/blob/0ab9348df873aff5143d462566d0c020a1dcc880/UABEAvalonia/AssetImportExport.cs#L214-L217) into regular non escaped line breaks, and the game is not able to correctly parse them (actually only the first line of the strings is shown in-game).

I think the following flow also confirms the unexpected behaviour:
1. Export the asset using "Export dump".
2. The resulting string has the escaped line breaks `\\n`.
3. Without making any change import the dump back to the asset.
4. Export the asset using "Export dump" again.
5. The resulting string has the line breaks unescaped `\n`.

Could this be a bug? Or is there any way to workaround the problem?

Thank you for your work.

**Comment by nesrak1** [comment]
Fixed in latest commit.
