### ISSUE TITLE
txt dump encoding

### ISSUE THREAD

**Issue by orangespoons** [nesrak1/UABEA#115]
When I extracted the Monovehaviour file using the program, the encoding was ANSI.
Can you update the program to use UTF-8 or UTF-8 BOM instead of ANSI when dumping to txt?
I'm editing the font's coordinate file, but I need utf-8 encoding to find out what kind of character it was originally made with.
Thanks.

**Comment by nesrak1** [comment]
I'm not sure what you mean, it seems to be exporting fine in UTF-8 for me. What field were you talking about in Font?

**Comment by orangespoons** [comment]
SDF font Monobehaviour file.
When I checked it again, it opened properly in the default notepad.
But in notepad++ it was opened in ANSI, so the characters were not displayed properly.
It's probably a notepad++ issue. sorry!
