### ISSUE TITLE
Edit object data,

### ISSUE THREAD

**Issue by TDBOfficial** [nesrak1/UABEA#119]
When selecting an asset you can view its data but why cant you edit the data? The only way i've found to edit the data is just exporting the dump and editing that with notepad and all i can edit with that that i found useful is just the visibility and name, When will we be able to edit the components of objects if possible?

**Comment by nesrak1** [comment]
Import/export dump/raw is the only way to edit assets (by that I mean the View Data dialog does not support editing), same as UABE. As for adding/removing components, you can edit the `m_Components` array and add or remove pointers to other assets. And if you need to make a new asset, you can create one in File->Add.
