### ISSUE TITLE
WHEN WILL THE NEXT UPDATE?

### ISSUE THREAD

**Issue by doidinmods** [nesrak1/UABEA#120]
WHEN WILL THE NEXT UPDATE?

**Comment by nesrak1** [comment]
I'm not sure what you mean. Is there a particular feature you want in a future update?

**Comment by doidinmods** [comment]
Not sure what you mean. Is there a specific feature you want in a future update?

**Comment by doidinmods** [comment]
yes, edit 3d mesh import dump files, when i import in game it is invisible

**Comment by doidinmods** [comment]
I work with mods using this a
UABEA and I need it updated to edit urgent 3d mesh

this is my youtube channel where I share my work using UABE

https://www.youtube.com/channel/UCLKF6CG6MyMPDf5VTYhRwnA

**Comment by nesrak1** [comment]
Mesh discussion in #124.
