### ISSUE TITLE
3D MESH EDIT 

### ISSUE THREAD

**Issue by luccaxPRO** [nesrak1/UABEA#122]
Hi, I'm trying to edit the 3d of a game made in unity version 2019.4.31.f1...Importing raw/dump, but when I open the game, the 3d doesn't show up, can you help me?

**Comment by doidinmods** [comment]
vc por aqui luccax kk um abraço man ta complicado esse negocio viu

**Comment by luccaxPRO** [comment]
@doidinmods eai mano, pois é mano tá dificil uma solução, tmj

**Comment by doidinmods** [comment]
vamo lutar pra conseguir isso ae
