### ISSUE TITLE
I have a question about the UABE

### ISSUE THREAD

**Issue by Sm982** [nesrak1/UABEA#123]
Hey,

I was wondering to the developer if I were able to reupload a version of the release to flmods.com , it’s a modding site for the game Flashing Lights. Sole purpose is to post it on the site for easy access and download for users. If not, all good. If so, credits will be everywhere on the download. 

Cheers

**Comment by nesrak1** [comment]
Answered in discord (yes you can share it anywhere you want, it's open source software)
