### ISSUE TITLE
Will export be a thing?

### ISSUE THREAD

**Issue by MacoDeVinx** [nesrak1/UABEA#127]
Hello, so with UABEA trying to mimic what UABE had, I've noticed it lacks the ability to export .dae and .obj files through Plugins which UABE did, my question is will this be a thing in the upcoming updates?

I did read through #124 where you said "I don't intend to write the mesh plugin anytime soon."

Is that the same answer to my question regarding being able to export models as .dae and .obj like you used to do through UABE?
Would be nice with something to go from considering the game we are modding has come to an end due to UABE not supporting newer Unity versions. 

And I did read #120 which had no real answer to their question on the matter.

Best Regards
MacoDeVinx

**Comment by nesrak1** [comment]
For now, I'm suggesting people to do fbx export through AssetStudio or similar tools. Reason being that UABE's mesh plugin was just that, a mesh without any textures or anything else, while AssetStudio can handle textures, bones, etc. (which is outside of just the mesh itself). It gets a bit complicated when you deal with those kinds of things and there's already something that can handle it well. Now it could be useful over AssetStudio if I decided to support importing later on, but I'm not sure yet.

**Comment by MacoDeVinx** [comment]
Sorry for the late response, understandable with AssetStudio in some situations. How we used UABE was we exported models from the game as .dae as we need the objects split up with each material assigned to each different parts (not merged like .FBX .OBJ would do) afterwards put them into Unity then extract with Export Dump (which works fine with UABEA) however when we then Import Dump on the game then the game crashes.

This crash happens when we are using UABE, as the game is now updated and UABE no longer supports this, it would be nice with an alternative that doesn't involve .FBX or .OBJ's

Our only way of modding:
Plugins > Export as .dae > Load up Unity > Save scene etc with all in it and build > open the .assests file wanted > Export Dump > Go back to the game, open up the files > Import Dump.

Actually, now that we are at it while trying to solve this problem. Does UABEA only support Unity 5-2020.3 or also earlier Unity builds like Unity 4-2019.4?

**Comment by nesrak1** [comment]
I'm not sure why fbx or obj from AssetStudio wouldn't work by importing it into the project, but if there's something that can't be done in AssetStudio, I don't mind adding it. It's just that I've personally not had the need for it. I haven't had much time lately and there's a lot of other issues that need to be prioritized so I'm not sure when I can get around to it.

> Actually, now that we are at it while trying to solve this problem. Does UABEA only support Unity 5-2020.3 or also earlier Unity builds like Unity 4-2019.4?

Not sure what you mean by to 2019.4 because 5-2020.3 includes 2019.4. As for Unity 4, it's not supported (by AssetsTools.NET). It's a lot of work, requires redoing a lot of code, and there's few people who actually need Unity 4 support.

**Comment by MacoDeVinx** [comment]
> I haven't had much time lately and there's a lot of other issues that need to be prioritized so I'm not sure when I can get around to it.

No worries, it's just that we have a big community for this game and would be sad to see some aspects be gone, of course, take your time. It would just be nice to know if there were certain plans in the near or far future for **Plugins** > **Export as .dae** within UABEA like UABE had.

> Not sure what you mean by 2019.4 because 5-2020.3 includes 2019.4. As for Unity 4

I don't know either then. Not sure what I was thinking at the time of writing it.

**Comment by nesrak1** [comment]
Mesh plugin PR is in #221 for obj, #111 has mesh import request and #60 for general FBX support. Closing for dupe. FBX is not out of the question, but I may choose a different format (like how AssetRipper is using gltf).
