### ISSUE TITLE
UABEA Not saving replaced texture (2020.3.21f1)

### ISSUE THREAD

**Issue by Drivium** [nesrak1/UABEA#128]
Downloaded latest UABEA build (as of 11/16/2021)

I've attached a video of my process to show what I'm experiencing. I replace a texture, then export it from the newly created data.unity3d file to verify it was replaced successfully, but the texture is unmodified. Seems to indicate it's not saving correctly.

https://streamable.com/q08p7w

Here is a copy of the game I'm trying to mod:
https://drive.google.com/file/d/1UXICFbYsta5Tc-r_at4YoWhOzitursaX/view?usp=sharing

**Comment by nesrak1** [comment]
Looks like I only have it saving the main file (only assets with file id 0) so you can only edit that texture if you open resources.assets. As for why, I'm not sure. Let me test what happens if I remove it.

**Comment by nesrak1** [comment]
I've removed the single file restriction so it should work if you edit it from a different file.

**Comment by nesrak1** [comment]
If this worked, let me know so I can close the issue.

**Comment by Drivium** [comment]
> If this worked, let me know so I can close the issue.

Where would I find the latest build? I looked for it, but the latest releases show last was August

**Comment by nesrak1** [comment]
It's at the top of the readme
https://nightly.link/nesrak1/UABEA/workflows/dotnet-desktop/master/uabea-windows.zip

**Comment by Drivium** [comment]
Confirmed working! Thank you! Amazing work.
