### ISSUE TITLE
problems when modifying a .bundle file

### ISSUE THREAD

**Issue by DarkChaosMaster** [nesrak1/UABEA#129]
I want to modify a .bundle file, but after I import dump and save the file, the game stuck when loading at 100% (it seems failed to load)
I have tried many times, even if I simply decompress and open the bundle file->click Info->find one asset->export dump->directly import the txt file just exported (without any modification) ->save file->save and replace game file, the game still can't load it porperly. 
But if I just use the decompressed .bundle file, the game loaded successfully.
Is there any problem with my steps? or it is a bug in the game? thanks.

**Comment by nesrak1** [comment]
This seems to be an issue a lot of people are having. Is it with a specific compression method or both?
I doubt it's an issue with your game though.

**Comment by DarkChaosMaster** [comment]
Thank you for your reply.
The compression method is LZ4, and there seems to be no issue with compression and decompression work because the game can load the decompressed file or recompressed file properly.
Maybe there is something wrong when decoding/encoding assets? 
(Some assets have their accurate name in AssetStudio, while in UABEA they were displayed as unnamed asset)
(Of course, it may be just an issue with the game itself)

**Comment by nesrak1** [comment]
So if I've got you right, the original decompressed bundle works fine, but if you export and import without changing and save, then that bundle stops loading in the game?

> Some assets have their accurate name in AssetStudio, while in UABEA they were displayed as unnamed asset

To make loading quicker, UABEA skips assets that don't have a name field as the first field without looking anywhere else for the name. So some assets like Shaders, MonoBehaviours, etc. won't display names. If you see almost no assets with names, then yes, there probably was an issue with reading the file correctly.

**Comment by DarkChaosMaster** [comment]
> the original decompressed bundle works fine, but if you export and import without changing and save, then that bundle stops loading in the game?

Yes.
> UABEA skips assets that don't have a name field as the first field without looking anywhere else for the name. So some assets like Shaders, MonoBehaviours, etc. won't display names.

That's it. thanks.

**Comment by nesrak1** [comment]
Can you post the output.log (or adb output) from the game? It's possible you're editing an addressable which fails to load due to the hashes not matching.

**Comment by DarkChaosMaster** [comment]
Here is the Player.log :
```
UnloadTime: 113.657500 ms
TypeManager.Initialize took: 401ms
CRC Mismatch. Provided d6646b7c, calculated 69a0aeaa from data. Will not load AssetBundle 'prefabs_assets_all_cfb4ef6014b05e70dcd132077f00be4e.bundle'

Exception encountered in operation Resource<IAssetBundleResource>(prefabs_assets_all_cfb4ef6014b05e70dcd132077f00be4e.bundle), status=Failed, result=UnityEngine.ResourceManagement.ResourceProviders.AssetBundleResource : 

Exception encountered in operation Dependencies [prefabs_assets_all_cfb4ef6014b05e70dcd132077f..., defaultlocalgroup_unitybuiltinshaders_aec055c...], status=Failed, result=System.Collections.Generic.List`1[UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle] : 

Exception encountered in operation Resource<GameObject>(water_solid.prefab), status=Failed, result= : Dependency Exception

Exception encountered in operation Resource<GameObject>(water_outside_3.prefab), status=Failed, result= : Dependency Exception

Exception encountered in operation Resource<GameObject>(water_outside_2.prefab), status=Failed, result= : Dependency Exception
```
( the following same exceptions are omitted )

**Comment by nesrak1** [comment]
> CRC Mismatch. Provided d6646b7c

Yes, it looks like an addressable, and it won't load because it doesn't match the right CRC (your bundle is probably valid then). I don't have the notes on me right now but you'll need to edit the catalog.json file and iirc there's a base64 string in it that has a list of crc32s that you can set to 0 to ignore the check.

I'll write steps later into how you can do that.

**Comment by nesrak1** [comment]
[updatecatalog.zip](https://github.com/nesrak1/UABEA/files/7590826/updatecatalog.zip)

Run this python script in the StreamingAssets/aa folder (next to catalog.json) and it should make a catalog_new.json file with CRCs disabled. Just replace the old one with the new one.

**Comment by DarkChaosMaster** [comment]
The script works fine. Thank you for helping me a lot! I really appreciate your great efforts to make UABEA more perfect.
