### ISSUE TITLE
UABEA not importing mesh correctly - (2020.3.21f1)

### ISSUE THREAD

**Issue by Drivium** [nesrak1/UABEA#130]
I'm trying to swap a mesh in an apk (Solar Smash). Here's a link to the apk:
https://drive.google.com/file/d/1UXICFbYsta5Tc-r_at4YoWhOzitursaX/view?usp=sharing

I'm attempting to swap one of the sphere meshes with a mesh of a different shape. Process seems to go fine (no errors), but doesn't seem to do it correctly.

AssetStudio error:
https://imgur.com/xKsSwYi

Also attempted to load into apk and run anyway. Runs, but mesh is definitely not the shape of my mesh:
https://imgur.com/XIUkqk

This is the dump produced when I export my new mesh to txt:
[default-CAB-eef5017a502494bc7809e46099cc68e7--555019651883009065.txt](https://github.com/nesrak1/UABEA/files/7590531/default-CAB-eef5017a502494bc7809e46099cc68e7--555019651883009065.txt). Then I import that over the target mesh. Dunno if naming matters. Target to replace is called "EarthShell" and my new txt (attached) is just called "default." I've tried naming it to match, but still breaks assetstudio. In case it matters, I'm attempting to swap with a mario head. I've attached the source obj (prior to building and extracting txt): [Mario.zip](https://github.com/nesrak1/UABEA/files/7590555/Mario.zip)

**Comment by nesrak1** [comment]
This was brought up in the discord just yesterday and it's because the mesh you imported depends on another file in `m_StreamData` (archive:/CAB-eef5017a502494bc7809e46099cc68e7/CAB-eef5017a502494bc7809e46099cc68e7.resS). Copy the resS file to the game directory and rename the field in the dump.

**Comment by Drivium** [comment]
I'm not sure I understand what m_StreamData and resS are or where to find them.  Also, I looked for the Discord link, but not seeing it.

**Comment by Drivium** [comment]
I just noticed these files inside my mariohead build: https://imgur.com/H4h8sXJ

I tried adding sharedassets0.assets.resS along side the data.unity3d, but the game wouldn't load. I think we're close, but might need help understanding.
