### ISSUE TITLE
Search not working, filtering assets by name and file type isn't possible as well

### ISSUE THREAD

**Issue by Sapphire8** [nesrak1/UABEA#134]
So an experimental build came out for 7 Days to Die, they've moved to Unity 2020 engine and old UABE stopped working obviously, so I found this app and it's a bit painful to import stuff for now since the search by name is broken (for example, if I want to find an audioclip called ak47_fire1, it would show me an error or show me a random GameObject instead. However, sometimes it does work :D). Then I thought that I would try to filter all this stuff by clicking name and file type, but it doesn't work like that, worked on old UABE tho.
Edit: did a little bit more testing with search by name, seems like if you change any of the filters, the search will break and show random results, sometimes it doesn't find the asset you've been looking for.

**Comment by nesrak1** [comment]
The search not working is an avalonia bug (yet to be fixed, see https://github.com/AvaloniaUI/Avalonia/issues/6766)

**Comment by nesrak1** [comment]
I might be able to make a bad hack with reflection temporarily. Will do more testing on it.

**Comment by nesrak1** [comment]
Reflection hack in, let me know if it works for you.

**Comment by nesrak1** [comment]
Closing this since search seems to be working fine for now.
