### ISSUE TITLE
problem with .Net6.0.1

### ISSUE THREAD

**Issue by kourain** [nesrak1/UABEA#153]
UABEA call me download .Net
![image](https://user-images.githubusercontent.com/85356599/153384709-8d936d94-f269-4e43-b507-07912165e6b9.png)
but my PC have .Net 6.0.1
![image](https://user-images.githubusercontent.com/85356599/153384890-675dcc85-847c-4a48-8416-f78748350db6.png)

**Comment by woctezuma** [comment]
The dialog window does not make it super clear which version of the .NET 5 downloads to pick: console or desktop?

![Versions](https://i.ibb.co/xmPgZtw/2022-03-29-14-47-22.png)

It turns out that the runtime for **desktop apps** is sufficient.
