### ISSUE TITLE
崩溃解决办法，建议作者加到说明里面 （Crash solution, it is recommended that the author add it to the description）

### ISSUE THREAD

**Issue by xdvsrs** [nesrak1/UABEA#154]
我在win10系统使用该软件时发现存在崩溃情况，WIN7系统测试却完全正常。
最终确定是系统缺失DLL导致，最简单处理办法，安装 微软常用运行库合集 即可解决问题

下载地址 https://www.mefcl.com/yxk-dreamcast/249

EN

When I use the software in win10 system, I found that there is a crash situation, and the test of WIN7 system is completely normal.
It is finally determined that it is caused by the lack of DLL in the system. The easiest way to deal with it is to install the Microsoft Common Runtime Collection to solve the problem.

Download address https://www.mefcl.com/yxk-dreamcast/249

**Comment by nesrak1** [comment]
I'll add a notice in the program if the user doesn't have the redistributable installed soon.
