### ISSUE TITLE
Uabe Window 7 is in use, but there's a collision with the photo saved.

### ISSUE THREAD

**Issue by cor45247** [nesrak1/UABEA#156]
![gg](https://user-images.githubusercontent.com/100107979/154887606-6988ea9d-8ea7-4605-ad2f-78ccc2446705.jpg)

Application: UABEAvalonia.exe CoreCLR Version: 5.0.1422.5710 .NET Version: 5.0.14 Description: The process was terminated due to an unhandled exception. Exception Info: System.DllNotFoundException: Unable to load DLL 'textoolwrap' or one of its dependencies: 지정된 모듈을 찾을 수 없습니다. (0x8007007E) at TexturePlugin.PInvoke.EncodeByISPC(IntPtr data, IntPtr buf, Int32 mode, Int32 level, UInt32 width, UInt32 height) at TexturePlugin.TextureEncoderDecoder.EncodeISPC(Byte[] data, Int32 width, Int32 height, TextureFormat format, Int32 quality) at TexturePlugin.TextureEncoderDecoder.Encode(Byte[] data, Int32 width, Int32 height, TextureFormat format, Int32 quality) at TexturePlugin.EditDialog.BtnSave_Click(Object sender, RoutedEventArgs e) at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state) at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33 at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37 at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210 at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg) at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 157 at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61 at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 107 at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 134 at UABEAvalonia.Program.Main(String[] args) in C:\Users\nesquack\Documents\GitRepos\uabequickfixes\UABEA\UABEAvalonia\Program.cs:line 47

**Comment by nesrak1** [comment]
You need to install the c++ redistributable https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by cor45247** [comment]
Thank you. I installed it and it works well. 
 
-----Original Message-----
