### ISSUE TITLE
UABE is not opening

### ISSUE THREAD

**Issue by nob2892** [nesrak1/UABEA#157]
When i open the UABEAvalonia.exe it's not opening and doesn't give a crash details but when i open Event viewer here's the details.
![Capture](https://user-images.githubusercontent.com/100210111/155236169-ebff9d2b-51d9-4317-9be4-75df827bdca7.PNG)
Sorry for my bad english

**Comment by nesrak1** [comment]
As the error suggests, you should install .net 5 (usually it gives you a popup to install).
You can find a download here: https://dotnet.microsoft.com/en-us/download/dotnet/5.0
Either .NET Runtime or .NET Desktop Runtime is ok.

**Comment by nob2892** [comment]
it didn`t work :(
![Capture](https://user-images.githubusercontent.com/100210111/156524108-81f5ef3d-c91c-4b15-a20e-938a823c09b8.PNG)
