### ISSUE TITLE
Crash when saving and closing bundle files (unity2021.2)

### ISSUE THREAD

**Issue by DarkChaosMaster** [nesrak1/UABEA#163]
My steps: open a file->info->select an asset->export->reimport->click 'save'->close the window->crashed
Here is the event log:

`Application: UABEAvalonia.exe CoreCLR Version: 5.0.1221.52207 .NET Version: 5.0.12 Description: The process was terminated due to an unhandled exception. Exception Info: System.IO.EndOfStreamException: Unable to read beyond the end of the stream. at System.IO.BinaryReader.InternalRead(Int32 numBytes) at System.IO.BinaryReader.ReadInt32() at AssetsTools.NET.AssetsFileReader.ReadInt32() at AssetsTools.NET.Type_0D.Read(Boolean hasTypeTree, AssetsFileReader reader, UInt32 version) at AssetsTools.NET.TypeTree.Read(AssetsFileReader reader, UInt32 version) at AssetsTools.NET.AssetsFile..ctor(AssetsFileReader reader) at AssetsTools.NET.Extra.AssetsFileInstance..ctor(Stream stream, String filePath, String root) at AssetsTools.NET.Extra.AssetsManager.LoadAssetsFile(Stream stream, String path, Boolean loadDeps, String root, BundleFileInstance bunInst) at UABEAvalonia.MainWindow.InfoWindow_Closing(Object sender, CancelEventArgs e) in D:\a\UABEA\UABEA\UABEAvalonia\MainWindow.axaml.cs:line 501 at Avalonia.Controls.Window.OnClosing(CancelEventArgs e) in /_/src/Avalonia.Controls/Window.cs:line 993 at Avalonia.Controls.Window.ShouldCancelClose(CancelEventArgs args) in /_/src/Avalonia.Controls/Window.cs:line 559 at Avalonia.Controls.Window.HandleClosing() in /_/src/Avalonia.Controls/Window.cs:line 514 at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs:line 62 at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.WndProc.cs:line 33`

**Comment by nesrak1** [comment]
What's the game version and if it's free, could I get a link to it?

**Comment by DarkChaosMaster** [comment]
The game uses unity2021.2, it's not free and the file is so large that I can hardly upload it. But It seems that I have found another solution by exporting the CAB file and editing it separately. Thanks for the concern.
