### ISSUE TITLE
Cannot mass import/export MonoBehaviours to/from .json

### ISSUE THREAD

**Issue by IlDucci** [nesrak1/UABEA#166]
If I want to export/import MonoBehaviors one by one via dumps, not raw format, there's an option to pick between TXT/JSON formats, but if I want to dump/import dozens of files, UABEA defaults to .TXT instead. The old UABE showed a window for these cases where you would be able to select the text format.

**Comment by nesrak1** [comment]
Are you on the latest nightly? This feature has already been added. Batch export and import both show a box to choose whether to use json/txt or in the case of import, both.

**Comment by IlDucci** [comment]
Sorry, I was on stable. Just checked the latest nightly and it does have that function. Again, my apologies.
