### ISSUE TITLE
having problem with opening a large(1.77gb) file

### ISSUE THREAD

**Issue by vlvkwls** [nesrak1/UABEA#167]
I tried to open a 1.77GB file, and it didn't work. It literally does nothing. 

It worked when I tried it with a much smaller one.

When it comes to that larger, it couldn't open, doing nothing and making no errors, so no stack trace was left.

Could you please assist me?

![1](https://user-images.githubusercontent.com/101483400/158059952-3cdb6134-6d80-4bc7-8ce9-3b34656c32b3.png)

unity version

![2](https://user-images.githubusercontent.com/101483400/158059986-e6ec6509-3d9f-4512-90c0-aa7508a7a7de.png)

targeted file

**Comment by nesrak1** [comment]
https://github.com/nesrak1/UABEA/wiki/Sending-a-crashlog

**Comment by vlvkwls** [comment]
Sorry, I don't know anything about programming at all. I am hoping this is what you said. Thank you.
![hexdumps](https://user-images.githubusercontent.com/101483400/158075789-a5eeb765-f9b4-4399-a530-0fd52cc8556a.png)

**Comment by vlvkwls** [comment]
> ~https://github.com/nesrak1/UABEA/wiki/Sending-a-crashlog~
> 
> Actually, you said it does nothing (not crash) so it's probably more related to detection than anything. Could you screenshot the hex dump of the top of the file?

Sorry, I don't know anything about programming at all. I am hoping this is what you said. Thank you.
![Uploading hexdumps.png…]()

**Comment by nesrak1** [comment]
Should be fixed in latest nightly.

**Comment by vlvkwls** [comment]
Thank you very much!
