### ISSUE TITLE
I have .NET though...

### ISSUE THREAD

**Issue by ToggledDerp** [nesrak1/UABEA#169]
![Screenshot (773)](https://user-images.githubusercontent.com/102929653/161452434-e46f68b2-0b25-4d87-8c14-eb56141428e5.png)

**Comment by ToggledDerp** [comment]
![Screenshot (774)](https://user-images.githubusercontent.com/102929653/161452664-b04ab22d-758b-49e1-88a6-a95409725c9e.png)

**Comment by nesrak1** [comment]
UABEA needs .net 5 specifically. If you have .net 6 it won't work. #153 probably.

**Comment by ToggledDerp** [comment]
How do I get that? I got Version 6 with Paint.NET

**Comment by nesrak1** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-5.0.15-windows-x64-installer

**Comment by ToggledDerp** [comment]
Thanks

**Comment by ToggledDerp** [comment]
Wow! It's a 32-bit file!
![Uploading Screenshot (775).png…]()

**Comment by ToggledDerp** [comment]
What
![Screenshot (778)](https://user-images.githubusercontent.com/102929653/161453370-8ee2aec4-898c-4786-8a1a-569052102e49.png)

**Comment by ToggledDerp** [comment]
What's wrong with .NET 5
![Screenshot (778)](https://user-images.githubusercontent.com/102929653/161453409-dcac189e-8341-4efe-8cfa-7aa4be1f47cc.png)

**Comment by nesrak1** [comment]
Have you tried restarting?

**Comment by ToggledDerp** [comment]
No

BUT
It IS a 32-bit file.
![image](https://user-images.githubusercontent.com/102929653/161453452-20e980ef-295b-4f67-b9f6-cefb1b2a1f81.png)

**Comment by ToggledDerp** [comment]
ok i'll try

**Comment by ToggledDerp** [comment]
Time to download the 64-bit version.

**Comment by nesrak1** [comment]
I gave you the 64 bit download link already. I even installed this in a clean VM and it worked fine without a restart.
