### ISSUE TITLE
Crash when starting to load a texture replacement then cancelling the dialog.

### ISSUE THREAD

**Issue by Nazosan** [nesrak1/UABEA#171]
I'm a bit surprised this hasn't come up already, but perhaps others make fewer mistakes in clicking through all the process (I've been processing a bunch of files at once on something) unless I just missed it in the search.  I've had a crash every single time if I used the edit texture plugin, clicked load, and then canceled the dialog box (usually if I get the wrong one or something like that.)  I've been using this with Rune Factory 5's bundle mess, but I think it's probably something that isn't version specific since it's the dialog cancel itself that causes the crash.  If I load some image and then cancel after that it's fine, it is only the open dialog box I must not hit cancel in.  On its own no big deal, but I've had a few times where I had changed a bunch of images first and then hit cancel and had to start over.

**Comment by nesrak1** [comment]
This was already reported in the discord and I'll fix it tomorrow. It's due to a fix in an Avalonia update (UI library) that makes canceling dialogs consistent across all platforms. And I stupidly forgot to change the code after updating them.

**Comment by Nazosan** [comment]
I figured it would probably be fixed pretty quickly, but thought I'd post it just in case.  Cheers on being so fast about it.

**Comment by nesrak1** [comment]
@Nazosan forgot to mention you but the issue should be fixed.
