### ISSUE TITLE
Texture import dialog box seems to have a click through.

### ISSUE THREAD

**Issue by Nazosan** [nesrak1/UABEA#172]
So one minor annoyance that I would consider to be super low priority is if you are importing a texture and double click a file in the open file dialog that pops up, it seems to have a click through effect.  That is to say that if the filename you're clicking on is over the area of any of the buttons in the edit texture dialog box (most frequently seems to be the colorspace option for me) then it passes a click through.  This is not an issue with anything else I've ever used (eg it's not a hardware or driver issue) but only in this.  I was thinking of it and trying to figure out how this could be happening if it wasn't a hardware issue and the best guess I have as a non-programmer is that the dialog box registers click release (mouse up I think most things call it?) as being a full click versus most requiring both a click (down I guess?) and a release.  This also has the side effect of many dialog options will not let you drag away if you misclick to prevent it from registering (normally if you accidentally click a wrong button or whatever, if you don't let go of the button you can drag away and then it won't register as a click in most software -- both Windows and Linux I believe -- as a somewhat standard behavior.)  This isn't letting you do that for most things, including menus.  I suspect they're both ultimately the same issue.

**Comment by nesrak1** [comment]
I haven't had this issue yet (I can try testing more tomorrow) but either way this is an Avalonia issue. I don't manually handle input events.

**Comment by Nazosan** [comment]
Oh, I also worded that a bit wrong.  It's specifically if you're double clicking a filename rather than clicking once then clicking open.  Over certain things such as the dropdown boxes it seems to click through when you double click.  And yes, I'm pretty sure it is related to how Avalonia is handling things.  (On this subject, it's too minor even to add a separate thing just for it, but it would be nice if we could double click things in menus such as "edit texture" rather than having to click once to select then click the ok button after.  The old UABE would let you do that, but of course it was using generic Windows dialog controls.)

**Comment by nesrak1** [comment]
I can replicate this problem (again, it's an Avalonia issue so the best I can do is make an issue of there.) I've never encountered this issue personally since the open dialog box never shows up over the texture edit dialog for me. So you can move the window away from the edit dialog if you don't want that to happen.

**Comment by Nazosan** [comment]
Strange.  It puts the box just over the window 100% of the time for me.  I can't imagine why it would differ between systems.

Anyway, yes you can move it away.  Or you can just click once and click open.  The problem is, if you're processing a lot of files -- not just one or two or something -- that starts to add up to a lot of extra effort and delay just to avoid a clickthrough.

**Comment by nesrak1** [comment]
> The problem is, if you're processing a lot of files

If you're importing more than one texture, you can just select all the assets you want to import at one time and select the folder where you can find those images.

**Comment by Nazosan** [comment]
I did not know that could be done.  Thanks for the tip.

**Comment by nesrak1** [comment]
I don't know if the bug still exists in the preview, but it's been reported to them.
