### ISSUE TITLE
Please add the "monobehaviour modification" function

### ISSUE THREAD

**Issue by StarLing-sketch** [nesrak1/UABEA#173]

**Comment by nesrak1** [comment]
You can already import dump monobehaviours.

**Comment by StarLing-sketch** [comment]
Yes, my environment is ill2cpp, after following the instructions, I can only use "Export Raw" and "Import Raw", using other features will directly flashback

> 您已经可以导入转储单一行为。

**Comment by nesrak1** [comment]
From the readme
https://github.com/nesrak1/UABEA#monobehaviours

**Comment by nesrak1** [comment]
If you still have issues, they will most likely be fixed by https://github.com/nesrak1/AssetsTools.NET/pull/75

**Comment by StarLing-sketch** [comment]
ok,I've done the job

**Comment by StarLing-sketch** [comment]
![屏幕截图 2022-04-15 140723](https://user-images.githubusercontent.com/63322542/163528665-e4567405-d599-4d4d-8296-99368db8f209.png)

**Comment by StarLing-sketch** [comment]
> 从自述[文件 https://github.com/nesrak1/UABEA#monobehaviours](https://github.com/nesrak1/UABEA#monobehaviours)
Error message ：System.ArgumentOutOfRangeException:“Non-negative number required. Arg_ParamName_Name”
