### ISSUE TITLE
I have a question 

### ISSUE THREAD

**Issue by oldsportsgit** [nesrak1/UABEA#174]
so you know the TexturePlugin that you remade? can you tell me how you did that? because i want to remake some other plugins like the AudioClip plugin for example

**Comment by nesrak1** [comment]
You can use the TextAsset plugin as a starting out point. It's pretty close to the bare minimum for a plugin.

**Comment by vale7z4387ruwrejmhsr** [comment]
ok if i can figure out how to make a specific plguin i will release it

**Comment by vale7z4387ruwrejmhsr** [comment]
so i did some other things but i started working on the audioclip plugin and this is what i have so far
[Program.txt](https://github.com/nesrak1/UABEA/files/8524951/Program.txt)
