### ISSUE TITLE
lost processing multiple assets files

### ISSUE THREAD

**Issue by Bxaa** [nesrak1/UABEA#177]
```
 private async void MenuOpen_Click(object? sender, RoutedEventArgs e)
         {
             OpenFileDialog ofd = new OpenFileDialog();
             ofd.AllowMultiple = true; --- <<< JUST ADD THIS
             ofd.Title = "Open assets or bundle file";
```

You lost a global multiple files processing at one operation, that fully supported (UABE)
<a href="https://ibb.co/B39Z5b7"><img src="https://i.ibb.co/54P8gmz/Multiple.jpg" alt="Multiple" border="0"></a>

**Comment by nesrak1** [comment]
It's being worked on, but it's harder than just adding the allow multiple option.

**Comment by Bxaa** [comment]
Everything works - just allow multiple (all code already is present)

**Comment by nesrak1** [comment]
The issue is mainly with the AssetsFile detection code being bad. It falsely tries to read files as AssetsFiles that aren't and causes crashes when someone just selects all files in a _Data folder.

**Comment by Bxaa** [comment]
Even if that's the case, it's a matter of seconds to fix. (with everything I've tried no glitches)
And yes, thank you very much for continuing to develop this tool.

**Comment by nesrak1** [comment]
Going to rework the function a bit and fix AssetsTools.NET#76 at the same time

**Comment by nesrak1** [comment]
That function needs more work, but if you need something right now check the latest build.

**Comment by Bxaa** [comment]
Thank you, if I catch any glitches I will report.

Also, suggestion:
Add selection of all elements by type (e.g. textures) by double-clicking on one of them in the list.
This function very useful for all.

Thx

**Comment by nesrak1** [comment]
Yeah, I was thinking a filter option on selection or by name would be nice to have.
