### ISSUE TITLE
Can't Import

### ISSUE THREAD

**Issue by xsoider** [nesrak1/UABEA#178]
After I selected Import Raw, I clicked on "Files" and saved it but when I use AssetStudio to review the file, it still doesn't work. And UABEA didn't even ask me where to save the file and name it.
Edit: It's happened in releases 3 and 4.

**Comment by nesrak1** [comment]
If you're editing a bundle, you need to click save in the assets info window and the bundle window. UABEA should warn you (in release 4) when you try to exit without saving. If nothing happens, most likely you didn't make any changes and UABEA has nothing to save.

**Comment by xsoider** [comment]
I imported raw but still nothing happen

**Comment by nesrak1** [comment]
Please join the discord at https://discord.gg/hd9VdswwZs for support with this.
