### ISSUE TITLE
I have run your last code.

### ISSUE THREAD

**Issue by ylegey** [nesrak1/UABEA#18]
Hello.
I was look your last version code,are you finish the plugin support?
I have run your code yet,but when I open the winform Plugin-Edit-Load-(choose a Texture)-Save,it tell me "System.DllNotFoundException:“Unable to load DLL 'D:\textoolwrap.dll' or one of its dependencies",I try put this textoolwrap.dll in  "UABEAvalonia\bin\Debug\net5.0" ,and my system32 folder,but no use.

**Comment by nesrak1** [comment]
Along with the textoolwrap64.dll (which you should rename to textoolwrap.dll), you'll also need to copy pvrtexlib.dll to the same place from pvrtexlib/windows_x86_64 in textoolwrap.7z.

Better instructions/build system will come soon.

**Comment by ylegey** [comment]
OK，thank you very mach.I was successed use the plugins,it do work well,I was learned a lot.Thanks share again,And look forward to your new version ^_^
