### ISSUE TITLE
can you upload a built version of uabea please

### ISSUE THREAD

**Issue by Kabis456789** [nesrak1/UABEA#187]
look cool , but i can't use it , why do people "release" useful tools , but you have to build them yourself? i don't know how to do that , why not just upload a built version along side the unbuilt one ?

**Comment by MonteePoke** [comment]
![chrome_5HODE1mm5C](https://user-images.githubusercontent.com/44632941/179396463-86ae96f2-7187-4505-80ef-4bce51c62f20.png)
?
https://github.com/nesrak1/UABEA/releases/tag/v4
