### ISSUE TITLE
Packing resources issue

### ISSUE THREAD

**Issue by AtsushiShiga** [nesrak1/UABEA#188]
Working on latest games fan-localisation
While trying to replace MonoBehaviour file with localisation, UABEA (the latest build) gives me negative path ID, and after changing even one single byte of text there and replacing it with a new one, the game enters endless black screen. This game is not  il2cpp-compiled. Filename - localize_assets_all_d32ca783d25393ad76183914c19258a8.bundle, it is from subfolder in StreamingAssets. It would be nice if this issue would be solved.

**Comment by nesrak1** [comment]
The issue is not with UABEA but the addressables CRC bit matching. See #129. I posted an updated python script in the discord to remove this check:

> https://cdn.discordapp.com/attachments/862035809795964969/927372959746768996/updatecatalog.py
> Run this python script in the StreamingAssets/aa folder (next to catalog.json) and it should make a catalog_new.json file with CRCs disabled. Just replace the old one with the new one.

**Comment by AtsushiShiga** [comment]
I thought it works fine, but it seems this script requires catalog.json and settings.json in the folder, but there is no catalog.json, only catalog.bundle + settings.json

**Comment by nesrak1** [comment]
Weird, but looking at the code you can remove the settings.json reading code and replace ab_directory's value with whatever.

**Comment by nesrak1** [comment]
I've heard of catalog.bundle but I don't think I have any games that use that yet. If I had to guess, if you open that bundle with UABEA you'll find a TextAsset with catalog.json inside.

**Comment by AtsushiShiga** [comment]
You're totally right. There is TextAsset, but whn I add it to folder for using script, it gives me another error
![JCejxwVimZ8](https://user-images.githubusercontent.com/99035724/180860275-b0b6278b-0c75-4f14-81a2-fa3e84bd8fda.jpg)

**Comment by nesrak1** [comment]
I'll try to find a game later today that uses this new catalog format and I'll get back to you.

**Comment by AtsushiShiga** [comment]
Thanks in advance!

**Comment by nesrak1** [comment]
Just to keep you updated, I'm making an addressables catalog.json/bundle editing library and will make it an automatic part of UABEA when you save any addressables bundle.

**Comment by AtsushiShiga** [comment]
Thanks! I'll be looking forward to it.

**Comment by AtsushiShiga** [comment]
Tried to deserialize catalog.json from catalog.bundle, and it ends with error using your new cleaning tool
![image](https://user-images.githubusercontent.com/99035724/220620964-d0546d99-4da5-419e-bc63-e825c978b788.png)

**Comment by nesrak1** [comment]
The game is probably an older version of Addressables (from an older version of Unity). I'm guessing `m_InstanceProviderData` doesn't exist in your json file.

I haven't yet figured out how the fields change over multiple versions, so if you want to help with that, feel free to.

**Comment by nesrak1** [comment]
Do you have Discord? It might be easier to work you through it on there.

**Comment by AtsushiShiga** [comment]
Well, it works now! Thank you for noticing my mistake!
