### ISSUE TITLE
Why not seem

### ISSUE THREAD

**Issue by ichalkorg** [nesrak1/UABEA#191]
Why can't I click on this file, please help me to open it, thank you.

![Help](https://user-images.githubusercontent.com/55353741/181481695-3fa8c2d7-b83f-47ec-9e51-8e18fb2a3401.png)

this is datapack.unity3d, please help me to open the info section
here : [link](https://drive.google.com/file/d/1tzBqFZ74DkdzAp7SFLR8oOV8pEJw4C9z/view?usp=sharing)

**Comment by nesrak1** [comment]
The game is probably using a newer version of Unity that UABEA normally supports. If you have visual studio you can build this branch: https://github.com/nesrak1/UABEA/tree/at3. Otherwise you have to wait.

**Comment by ichalkorg** [comment]
how long should i wait? because i really need it

**Comment by nesrak1** [comment]
When it's done. Again, if you really need it you can build it yourself.

**Comment by ichalkorg** [comment]
I don't understand programming, I can only make mods, can you help me?

**Comment by nesrak1** [comment]
Here's a build. I'm not offering any support on it if it doesn't work right now. [net6.0.zip](https://github.com/nesrak1/UABEA/files/9215451/net6.0.zip)

**Comment by ichalkorg** [comment]
does not work, still the same. please try the file.
[this is the file](https://drive.google.com/file/d/1tzBqFZ74DkdzAp7SFLR8oOV8pEJw4C9z/view) try it.

**Comment by nesrak1** [comment]
Still the same "This doesn't seem to be a valid file" message? Normally this is caused by newer versions of the game, but if you're still getting it then I don't know what to tell you, other than your game files might be encrypted.

**Comment by nesrak1** [comment]
[net6.0.zip](https://github.com/nesrak1/UABEA/files/9215586/net6.0.zip)

**Comment by ichalkorg** [comment]
> [net6.0.zip](https://github.com/nesrak1/UABEA/files/9215586/net6.0.zip)

oh my god, this worked.
thank you very much friend, may your fortune continue to grow. Once again, thank you.
