### ISSUE TITLE
Force close

### ISSUE THREAD

**Issue by ichalkorg** [nesrak1/UABEA#192]
after i edit and save it, the program closes forcibly when i click exit.
please fix it, thank you.

![Force close](https://user-images.githubusercontent.com/55353741/181675970-11c17a50-07d0-4a79-9bbd-346c09eeae28.png)

**Comment by nesrak1** [comment]
I still haven't done enough testing on at3 yet, but here should be a fix for that issue: [net6.0.zip](https://github.com/nesrak1/UABEA/files/9215959/net6.0.zip)

**Comment by ichalkorg** [comment]
here also seems to be fixed, all File ID 0, please fix it, thank you

![File ID](https://user-images.githubusercontent.com/55353741/181680974-d581040c-1dbc-425c-aa51-9af3c3dbb796.png)

**Comment by nesrak1** [comment]
If you're only seeing ID 0 but the dependencies list shows more than one item, it might be on disk and not in the bundle. I think UABEA should load it if the file is in the same directory as the bundle, but as this is the beta version it could just not be working right now.

**Comment by ichalkorg** [comment]
If it has been fixed, please provide information to me, thank you.

**Comment by ichalkorg** [comment]
how to import files that are in the Resources/ folder so that the files you want to import remain in the Resources/ folder?
![Resources](https://user-images.githubusercontent.com/55353741/181703788-5bdcf9fc-6884-4a0a-bb07-9935cc35c1e3.png)
