### ISSUE TITLE
Please add support .ab

### ISSUE THREAD

**Issue by ATLANTISans** [nesrak1/UABEA#194]
In the game that I want to modify, there are several apk files combined in .apks, in one of these apk (split_install_time.config.astc) I found files with the extension .ab is on the way assets/bundles/android and I do not know how to find out what is in these files, please add the ability to open these files.
This is the game I want to modify: https://t.me/EasyAPK/17905

**Comment by nesrak1** [comment]
If you can't open the file, it's probably encrypted.

**Comment by ATLANTISans** [comment]
I don't think they are encrypted, I think uabea just can't open them, now I'll send a link to google drive.

**Comment by ATLANTISans** [comment]
link to apk file https://drive.google.com/file/d/1i_-gUszAh7d6emnCEaE3H3Aj6FCCeo4l/view?usp=sharing

**Comment by ATLANTISans** [comment]
I really hope that support for .ab asset bundles will be added in the next updates

**Comment by nesrak1** [comment]
The files are encrypted. For reference, you should check with AssetStudio first to see if it errors there too.
