### ISSUE TITLE
 crash on 2021.3.11f1 can't open data.unity3d

### ISSUE THREAD

**Issue by c01ns** [nesrak1/UABEA#198]
packageName：com.GameCoaster.DungeonSquad
version：0.86
download path: https://apklust.com/en/dungeon-squad-apk

**Comment by nesrak1** [comment]
Have you tried at3 nightly?
https://nightly.link/nesrak1/UABEA/workflows/dotnet-desktop/at3/uabea-windows.zip

**Comment by c01ns** [comment]
thanks! this version can use!
