### ISSUE TITLE
How Do I Run UABEA

### ISSUE THREAD

**Issue by Kieran3101** [nesrak1/UABEA#2]
I have installed all the necessary files and have failed to find out how to run it

**Comment by nesrak1** [comment]
Did you download the release zip (not repo source code)? Are you on windows or linux? Does opening the exe work? I don't know what you've tried.

**Comment by Kieran3101** [comment]
i am so sorry for wasting your time I just found it thankyou for everything have a nice day!

**Comment by fuyumibaaka** [comment]
How do I open the UABEA program on Linux?
