### ISSUE TITLE
When TexturePlugin exports a picture, if the picture is large, it will cause the software to crash and exit

### ISSUE THREAD

**Issue by mskgroup** [nesrak1/UABEA#20]
When TexturePlugin exports a picture, if the picture is large, it will cause the software to crash and exit

**Comment by nesrak1** [comment]
I need a little bit more information to go off of.

How big is the image? What format is it? (you can check in the texture edit plugin) Does it crash with smaller images as well?

**Comment by mskgroup** [comment]
Size: 16777336
it's png
There is another problem. I don’t know where to put textoolwrap, so the exported pictures are garbled
![1](https://user-images.githubusercontent.com/51709279/116511182-a0ea5680-a8f8-11eb-82e8-af5cd3b4746d.png)

**Comment by nesrak1** [comment]
For size and file format I don't mean the file size or the format you're exporting, rather the texture dimensions and format. For example, 4096x4096 and DXT5 format. Again, you can find these in the edit texture plugin window.

Anyway, I figure if you're getting any image output, it's dxt since it's the only one not native. I realize that rgba is flipped (since that decoder is supposed to be used with c# bitmap, no imagesharp)

**Comment by mskgroup** [comment]
4096*4096 alpha8
![屏幕截图 2021-04-30 161253](https://user-images.githubusercontent.com/51709279/116667649-03ae2180-a9cf-11eb-8f2b-4c7533b11423.png)

**Comment by nesrak1** [comment]
The first image is a 1024x512 image, so I think this 4096x4096 image is something else.

For DXT images like the first image you posted, this bug has been fixed. I made a mistake where c++ and c# were both trying to convert from DXT. For everything else like Alpha8 in your second screenshot, that all uses pvrtexlib right now. You need to copy both textoolwrap64.dll and pvrtexlib/windows_x86_64/pvrtexlib.dll from textoolwrap.7z to the same folder as UABEAvalonia.exe, and then rename textoolwrap64.dll to textoolwrap.dll.

Anyway, I'm still working on the plugin, this is not a release and still needs a lot of testing still so don't expect anything to work well.

**Comment by mskgroup** [comment]
Yes, the above image can be exported, but the software will crash when exporting 4096*4096
