### ISSUE TITLE
Edit Location?

### ISSUE THREAD

**Issue by raphaelreal** [nesrak1/UABEA#205]
How to edit GameObject Location

**Comment by nesrak1** [comment]
I assume you're talking about GameObject transform position? The easiest way to do this is to click view data on the gameobject, open the first component (which is always transform), right click on `Transform Base` and click Visit Asset.

![image](https://user-images.githubusercontent.com/12544505/204160636-cc7dcd9c-3a0f-42cf-891c-46e979a212ac.png)

Then back in the info window, click export dump, save it somewhere, edit the position with a text editor, and import dump.

![image](https://user-images.githubusercontent.com/12544505/204160649-651d23de-3fcf-43e4-9d3a-93ca5f7c5cd6.png)

Then save like normal and it should have moved the GameObject's position.

**Comment by raphaelreal** [comment]
Awesome! Thanks! 🙏
