### ISSUE TITLE
Batch import assets to bundles

### ISSUE THREAD

**Issue by scese250** [nesrak1/UABEA#209]
Hello! I have a dozen of assets files that I want to import back to its respective bundle file, I used batchimportbundle but it won't import the modified asset

![image](https://user-images.githubusercontent.com/12405564/208155390-7c899b8b-27b7-4606-a1eb-b6bd449075e6.png)

**Comment by nesrak1** [comment]
The person who sent the files for batch import/export apparently did not add the batch import option and I didn't check this before making the release. This is one of the features I plan on fixing (adding) soon.
