### ISSUE TITLE
MonoBehaviour cannot dump normally

### ISSUE THREAD

**Issue by mskgroup** [nesrak1/UABEA#21]
MonoBehaviour cannot dump normally, it seems that the program does not automatically load the dll file in Managed.
But occasionally it can be dumped successfully, most of the time it can’t succeed.

**Comment by nesrak1** [comment]
This is not a bug, just not implemented, see todo list. Only bundles come with type trees. Plain assets files don't. This will come when dependencies are implemented.

**Comment by mskgroup** [comment]
very thanks for you

**Comment by nesrak1** [comment]
latest build should have monobehaviour deserialization
