### ISSUE TITLE
How do I edit all files at once?

### ISSUE THREAD

**Issue by Rayforward** [nesrak1/UABEA#213]
I want to revise [MonoBehaviour : TMPro.TextMeshProUGUI] file in bulk
How to import and export files in batches, just like selecting "Select all" in UABE? 
As far as I can see, a single unity3d file splits into a dozen, such as "globalgamemanagers", "sharedassets0.assets".
Await your answer with respect and trepidation

**Comment by nesrak1** [comment]
I didn't realize UABE now had a select all option. In any case, I recommend using filter (ctrl+i) to filter by MonoBehaviour. Then you can sort by name and select all assets with TextMeshProUGUI in the name. Select the first one, scroll down to the last one, hold shift and click it. Then you can batch export/import however you want.

Also, if you are trying to import UABE json dumps, they aren't compatible. I use a different format than UABE does. Text dumps are still the same though.

**Comment by Rayforward** [comment]
Thank you for your prompt reply, although I didn't know about it until I had slept on it XD
Let me explain further: I want to localise the game by editing hundreds of [MonoBehaviour: TMPro.TextMeshProUGUI] in [data.unity3D]. When I opened [data.unity3D] with UABEA, it showed me a dozen files like "globalgamemanagers", "sharedassets0.assets" in a drop-down box, and I could only view or batch edit one ata time (after clicking "info").
What I would like to ask is whether there is a way to view or edit all files in [data.unity3D] at the same time.
Or do I actually need to open a dozen contents of [data.unity3D] at the same time after fully opening it through "export all", and then integrate them back into [data.unity3D] at the end?

**Comment by nesrak1** [comment]
Yes, UABEA is based on UABE 2.2 which had the dropdown to select a file and its dependencies. That means that if you open something used by a lot of files (such as globalgamemanagers.assets or resources.assets), you will get a bunch of dependencies in the list as well, just not all of them. When you click info on a file, you can check if it's the file you opened or a dependency because the file you opened will have file id 0, whereas dependencies will have file id 1 and above.

In the future, I plan to redo the UI to allow you to select as many files as you want, but I'm still sort of waiting for Avalonia - the UI library - to make its update to 11.0 before I do so.

**Comment by Rayforward** [comment]
Sincere thanks！

**Comment by Rayforward** [comment]
I finally found the answer!
The way to do this, as I said, is to use "Export All" to export [data.unity3d] to the xxxxxxdata folder of the game (if you export it elsewhere and paste it back, the game will not work, which is strange), then move [data.unity3d] elsewhere and the game will still work. Now using uabea to open dozens of exports of [data.unity3d] at the same time makes you can edit all of its（[data.unity3d]） content at the same time！
Maybe someone else needs this information?

Of course, I must thank you again for making UABEA this wonderful tool! UABE cannot edit [MonoBehaviour: TMPro.TextMeshProUGUI] content, which is a minor pity.

**Comment by nesrak1** [comment]
Interesting. I didn't realize you could extract everything and it would recognize it. Glad you got it working. I still hope to have import all working in the future though.
