### ISSUE TITLE
How to open multi files?

### ISSUE THREAD

**Issue by eliteforcevn** [nesrak1/UABEA#215]
like tile im looking for a tutorial about open multi files? thanks :3

**Comment by nesrak1** [comment]
Are you talking about opening multiple bundles or multiple serialized files (sharedassets/level/resources.assets/globalgamemanagers/etc)? If they are serialized files, you can choose more than one file to open in the open file dialog or drag multiple files into the window.

**Comment by eliteforcevn** [comment]
thanks i want to open many .unity3d files to choice which i want to export i try select all of them in open file dialog but only last file is loaded :D

**Comment by nesrak1** [comment]
Only one bundle is supported at the moment. This is a well requested feature that mainly depends on updating the GUI (i.e. there is no technical issue)

**Comment by nesrak1** [comment]
You replied to the batch export issue which is potentially a solution. However, it might take up a lot of ram to load every bundle in your game.

**Comment by eliteforcevn** [comment]
thanks where i can get the batch commands :3

**Comment by nesrak1** [comment]
If you run uabeavalonia from the command line, it will print the documentation. It's the exact same as UABE's if you've used it before.
