### ISSUE TITLE
2020.3 support

### ISSUE THREAD

**Issue by mdsitton** [nesrak1/UABEA#23]
Currently 2020.3 isn't working properly, the application just immediately closes from my testing.

**Comment by nesrak1** [comment]
I don't have any unity 2020.3 games at the moment, but could you get the stack trace after it crashes ([like here](https://github.com/nesrak1/UABEA/issues/15#issuecomment-826471729))?

**Comment by nesrak1** [comment]
#29

**Comment by mdsitton** [comment]
Tested the latest release, and i still get the same crashing behavior this should be reopened

![image](https://user-images.githubusercontent.com/212897/120912427-8ff9d700-c654-11eb-9d4a-946b2b309cec.png)

**Comment by nesrak1** [comment]
This fix was made after release 2 was made, the changes should be in the [latest build](https://nightly.link/nesrak1/UABEA/workflows/dotnet-desktop/master/uabea-windows.zip).

**Comment by mdsitton** [comment]
Ah i see yeah it does indeed work now, thanks!
