### ISSUE TITLE
Support for DXT5 Crunched

### ISSUE THREAD

**Issue by 123qq1** [nesrak1/UABEA#235]
Support for editing textures with the DEXT Crunched format

**Comment by nesrak1** [comment]
What happens if you try to edit a DXT5 crunched texture? Support should be added for this already.

**Comment by 123qq1** [comment]
Edit texture does nothing, no error, while export texture gives error
![image](https://user-images.githubusercontent.com/39529815/230787898-8c9d34c2-9ad4-4028-91e1-f8e723b440f4.png)

**Comment by nesrak1** [comment]
Do you have the C++ redistributables installed? https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by 123qq1** [comment]
I tried installing it, restarted, still get the same error

**Comment by nesrak1** [comment]
Just to double check, are you using nightly? If you aren't using it, you should try that instead of release 5.

I installed nightly and tried myself and on both old and new engine games, I'm not having any issue exporting or importing crunched textures.

**Comment by 123qq1** [comment]
Thanks switching to nightly version works. Sorry i didnt mention what version i was running.
