### ISSUE TITLE
The save button isn't working properly, is it an issue?

### ISSUE THREAD

**Issue by roffyy** [nesrak1/UABEA#24]
![image](https://user-images.githubusercontent.com/82827017/117146185-4f274d80-ad8a-11eb-9de7-bbd8580dfa2d.png)

**Comment by nesrak1** [comment]
I forgot to update the modified * to hide when saved, but it may still be saving. Make sure you save the bundle as well after closing out of the info window.

**Comment by roffyy** [comment]
> I forgot to update the modified * to hide when saved, but it may still be saving. Make sure you save the bundle as well after closing out of the info window.

i saved the file after close the windows and the changes weren't save

**Comment by nesrak1** [comment]
Are you using the release or building from source?

**Comment by roffyy** [comment]
i'm using the release rn

**Comment by nesrak1** [comment]
The first release didn't have bundle writing, only asset writing. You'll either need to build from source or wait for another release (coming soon I hope)

**Comment by roffyy** [comment]
how can i build from source code? can u help me with that?

**Comment by roffyy** [comment]
i tried to build from the source code a few hours ago and it appears from the output
![image](https://user-images.githubusercontent.com/82827017/117192549-3df53580-adb8-11eb-98cc-ee61c8ab1637.png)

**Comment by roffyy** [comment]
> i tried to build from the source code a few hours ago and it appears from the output
> ![image](https://user-images.githubusercontent.com/82827017/117192549-3df53580-adb8-11eb-98cc-ee61c8ab1637.png)

so do i need reference all the assemblys?

**Comment by roffyy** [comment]
so do i need reference all the assemblys?
