### ISSUE TITLE
When i save something it goes nowhere and i need to find it

### ISSUE THREAD

**Issue by memiguel555** [nesrak1/UABEA#241]
so basically everytime i save something i can never find it and this causes alot of problems this could be a bug or im just dumb but please help out here

**Comment by nesrak1** [comment]
It would have been nice if you had followed the issue template so I could see what you tried and didn't try. All I know from this is that you tried to save but you couldn't find the file. You didn't tell me what type of file you tried to save, how you tried saving, or what assets you modified in the file and how you did it.

**Comment by memiguel555** [comment]
i tried to save a level0 file by pressing file then safe and ok but i never know where it goes.

**Comment by nesrak1** [comment]
Assuming you actually edited any assets in the level file, it will overwrite the original level0 file with the new changes.

**Comment by memiguel555** [comment]
everytime i save all the edited work is just gone

**Comment by memiguel555** [comment]
i was modifying it

**Comment by memiguel555** [comment]
and all of the stuff is in data.unity3d

**Comment by nesrak1** [comment]
The latest version of UABEA does not let you exit the bundle screen (the first window that pops up where you opened data.unity3d) without asking if you want to save, so if you missed that, that's on you.

**Comment by memiguel555** [comment]
so your saying i cant save because i missed it?

**Comment by memiguel555** [comment]
so i modified level 0 and then saved it and then saved the data.unity3d itself so now where do i find the file?

**Comment by memiguel555** [comment]
everytime i try to compile it says "You've modified this file, but only the old file before you made changes is open. If you want to compress the file with 
changes, please close this bundle and open the file you saved. Click Ok to compress the file without changes." but i want to select my modded file but i dont know where to get it do you know?
