### ISSUE TITLE
crash when export monobehaviour (unity 2021.3.16f1)

### ISSUE THREAD

**Issue by luatsenpai** [nesrak1/UABEA#243]
crash log:
Faulting application name: UABEAvalonia.exe, version: 1.0.0.0, time stamp: 0x641cef7e
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2546, time stamp: 0xe8e9ac9b
Exception code: 0xe0434352
Fault offset: 0x000000000002cd29
Faulting process id: 0x2c14
Faulting application start time: 0x01d9801aa619274a
Faulting application path: E:\uabea_rel4_windows_x64\UABEAvalonia.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 10f4c553-a297-4951-84af-62b4188085a8
Faulting package full name: 
Faulting package-relative application ID:

**Comment by nesrak1** [comment]
As the default template states, I only support nightly for bug reports and not release 4 (which was two entire releases ago)

**Comment by luatsenpai** [comment]
Oh sorry, it's just folder name, not uabe v4 but latest version and it shows error like above when i dump monobehaviour

**Comment by luatsenpai** [comment]
oh sorry it's just folder name, not uabe v4 but latest version and it shows error like above when i dump monobehaviour

**Comment by nesrak1** [comment]
You need to post `uabeacrash.log` then. I can't do anything with a basic native error message like that. There should have also been an error popup box that you could've copied from if you were on the latest release (6).
