### ISSUE TITLE
I can't open This *.bundle file? Can we do something?

### ISSUE THREAD

**Issue by PokemonUnite129** [nesrak1/UABEA#246]
Hi! This file is Unity 2019.4.15f1
And I got this file from Pokemon Unite.
When I try open them I got big problem like image
All file bundles from this game got the same error. Are they encrypted?
Url File: https://drive.google.com/file/d/1-HaEv_JnXLgLxTcmxUZRIMJ6BqfEWQfq/view?usp=sharing
![image](https://github.com/nesrak1/UABEA/assets/113233727/b9c4665e-f697-408c-b2e9-bc6d338a0ed9)

**Comment by nesrak1** [comment]
Unite is known for being encrypted. Decrypting it is something I won't add to uabea.

**Comment by PokemonUnite129** [comment]
Wait! Wait! Don't close! @.@.  Can you support this game for me personally?
Is that okay? I can pay for this. And do you have Discord?
