### ISSUE TITLE
Audio Import Support?

### ISSUE THREAD

**Issue by SergooPoke** [nesrak1/UABEA#247]
Recently i've been attempting to modify some sound files on We Love Katamari Reroll, more specifically, the level themes from the game. Said themes are stored in their own .bundle files (which contain the song and, oddly enough, another bundle)
![Cap1](https://github.com/nesrak1/UABEA/assets/134065351/7c74e314-6e5e-4f82-9fbf-f742032aa2a3)

At a first glance, this issue seems similar to #226. In that post it was mentioned that the UABE guide would work in this situation, but once I try the UABE method (by extracting the assets/resource from the .bundle, editing the assets file via UABE and re-importing the assets/resource to the .bundle in UABEA) the game simply doesn't recognize the new song and plays nothing. Furthermore, when I delete the old, unedited assets to let the new ones take their place it stops recognizing the assets file.
![Cap2](https://github.com/nesrak1/UABEA/assets/134065351/ae7346ee-27ba-4a0f-8c56-ca81f779de85)

Is it possible to add a way for UABEA to directly import and export StreamingAssets like UABE? Is what I'm attempting to do even possible at this point?

One final thing, I really apologize if this isn't really the place for this. I don't even know where to ask, and this seemed like the best place.

**Comment by nesrak1** [comment]
This _is_ pretty much #226 if you're just asking for a plugin to import audio directly. If I understand correctly, you're exporting both the assets file and the resource file, editing the assets file with UABE by right clicking the stream field and importing file (the fsb file). You then save as a new file, import the new assets file with UABEA, then delete the old file name. Did I get that right? Do you just not reimport .resource at all? What are you selecting for the "is serialized?" dialog?

**Comment by SergooPoke** [comment]
>What are you selecting for the "is serialized?" dialog for either?
> 
> If the file name you're importing is already in the bundle, UABEA should overwrite the original file. I wouldn't suggest renaming the files from their original.

Seems I was marking the assets file as serialized during the entire process. This time i marked it

**Comment by nesrak1** [comment]
I'm surprised that worked. Serialized file == assets file (serialized file is the official name, assets file is what uabe and uabea call it, except for this dialog). So the assets file should've been serialized and the resource file should've been non serialized.

> Hopefully one day a better way of exporting is implemented :P

Export all/import all is a thing that covers all of this (assuming file names are the same). I'd like to hear what way you are thinking of if you have any idea how to improve it.

**Comment by SergooPoke** [comment]
> Export all/import all is a thing that covers all of this (assuming file names are the same). I'd like to hear what way you are thinking of if you have any idea how to improve it.

Sorry about that, I meant exporting audio specifically. The current options to import and export assets seem perfect at the moment :)
