### ISSUE TITLE
Something went wrong when reading the dump file

### ISSUE THREAD

**Issue by qq2161392192** [nesrak1/UABEA#248]
Input string was not in a correct format.

**Comment by nesrak1** [comment]
Generally, this means your dump was not formatted correctly. Without providing any more information about how you modified it, how it looks, or any of the rest of the error message, I couldn't tell you what part of it wasn't formatted right.

**Comment by qq2161392192** [comment]
It seems to be caused by the game itself, and there is no problem with a small batch of imports

**Comment by qq2161392192** [comment]
> 通常，这意味着您的转储格式不正确。如果不提供更多关于如何修改它、它看起来如何或者错误消息的任何其他信息，我无法告诉您它的哪一部分格式不正确。

It turned out that WIndows PowerShell editing and saving caused encoding errors
