### ISSUE TITLE
Editing a .bundle file

### ISSUE THREAD

**Issue by santroy** [nesrak1/UABEA#252]
Hello

I am not an expert in this, I want to replace a text in a game that is in a prefab file in a .bundle (CAB).

![image](https://github.com/nesrak1/UABEA/assets/20000728/5669d722-0b00-4ec0-a9bb-0160eef94936)

I used UABEA to unzip a container, then dumped, edited and imported a monobehaviour file back. I next compressed the modified bundle and unfortunately the game freezes at the very beginning. The game behaves in the same way as if an entire .bundle file is missing.

I have tried decompressing and compressing the bundle without any changes and that does not cause problem. 

I also made a change in a hex editor, a very small one, because I only changed an uppercase to lowercase in the desired text and also the game can't turn on properly.

**Comment by nesrak1** [comment]
This is most likely an addressables crc issue. See the readme for info on this.

**Comment by santroy** [comment]
> This is most likely an addressables crc issue. See the readme for info on this.

It worked. Thank you very much for the hint.
