### ISSUE TITLE
Audio Import

### ISSUE THREAD

**Issue by BurAndBY** [nesrak1/UABEA#258]
**Is your feature request related to a problem? Please describe.**
Not really. There is a very frustrating way to import audio, but it requires rebuilding another game each time you need to edit an audio

**Describe the solution you'd like**
Make a import audio button that can import OGG/WAV files

**Additional context**
When audio is encoded in Unity the main options for how it is stored on disk is either PCM, ADPCM or Compressed. Additionally there are a few platform-specific formats, but they work in similar ways. *From Unity Wiki*

**Comment by nesrak1** [comment]
#136, #181, #226. Creators is looking into a native solution in the Discord, although I would rather have a managed one so I don't have to manage another set of native libraries.
