### ISSUE TITLE
build TexToolWrap error

### ISSUE THREAD

**Issue by mskgroup** [nesrak1/UABEA#26]
错误	LNK1120	1 个无法解析的外部命令	TexToolWrap	D:\Users\Pozet\Downloads\Compressed\UABEA-master\UABEA-master\Debug\TexToolWrap.exe	1	

错误	LNK2019	无法解析的外部符号 _main，函数 "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ) 中引用了该符号	TexToolWrap	D:\Users\Pozet\Downloads\Compressed\UABEA-master\UABEA-master\TexToolWrap\MSVCRTD.lib(exe_main.obj)	1	

Google Translate：
error LNK1120: 1 external command that cannot be resolved   TexToolWrap  D:\Users\Pozet\Downloads\Compressed\UABEA-master\UABEA-master\Debug\TexToolWrap.exe	1

error LNK2019 unresolved external symbol _main, This symbol is referenced in the function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)  TexToolWrap  D:\Users\Pozet\Downloads\Compressed\UABEA-master\UABEA-master\TexToolWrap\MSVCRTD.lib(exe_main.obj)	1

**Comment by nesrak1** [comment]
Make sure the project is set to build in x64 rather than Any CPU.

**Comment by nesrak1** [comment]
Build process should be a bit better now so try again with the latest commit

**Comment by mskgroup** [comment]
thanks very much
