### ISSUE TITLE
The AssetBundle could not be loaded because it references scripts that are not compatible with the currently loaded ones. Rebuild the AssetBundle to fix this error.

### ISSUE THREAD

**Issue by bean-sprout1** [nesrak1/UABEA#260]
When I try to load asset bundles from other games in the Unity editor, I encounter this error. I would like to know if this tool currently supports removing script-related information to resolve this problem.
assetBundle: [c0056.asset](https://github.com/bean-sprout1/otherfiles/blob/main/c0056.asset)
[nikki.prefab](https://github.com/bean-sprout1/otherfiles/blob/main/nikki.prefab)

**Comment by nesrak1** [comment]
It's a lot more complicated than you think to use different games' bundles together. While it's not supported right now, a bundle merging plugin is something I plan on in the future.

**Comment by bean-sprout1** [comment]
Later, I bypassed this error by manually modifying the hash. I look forward to further improvements in the tool as manual changes are cumbersome.

**Comment by nesrak1** [comment]
Renamed the MonoScript hash or the internal CAB name hash? Generally changing the MonoScript hash is a bad idea because you won't have the right fields that Unity expects for your game.
