### ISSUE TITLE
Asset failed to deserialize

### ISSUE THREAD

**Issue by lostprophet** [nesrak1/UABEA#264]
Tried both the stable and nightly version of UABEA to export the text dump from a MonoBehaviour file. When doing so, I get a very small txt file with the "Asset failed to deserialize." error message. (My goal is to translate the game, and the one on the screenshot is one of the files containing the game's texts).

The game is Alaloth: Champions of The Four Kingdoms. The file is in a big, 400 MB resources.assets file. Please let me know, if I can upload anything, that could help fixing this issue(?).

![kép](https://github.com/nesrak1/UABEA/assets/1469456/15a2c77b-efdb-479f-a328-8488711b0280)

**Comment by nesrak1** [comment]
Could you join the Discord server so I can walk you through this?

**Comment by nesrak1** [comment]
Fixed, yet another cpp2il issue.
