### ISSUE TITLE
Export plugin bug

### ISSUE THREAD

**Issue by TheSingleOneYT** [nesrak1/UABEA#27]
(I am just assuming this is a bug, it may still be being worked on)

You can only export one asset at a time, if you try multiple, one file is constantly being overwritten with another and so on.
I assume this is probably because you have to specify a name when exporting at the moment.

Thanks.

**Comment by nesrak1** [comment]
Yes, only single file export/import is supported at the moment. The grid will still let you select multiple, but only the first one will be used.

**Comment by TheSingleOneYT** [comment]
Ok thanks.
