### ISSUE TITLE
Batch import textures

### ISSUE THREAD

**Issue by TheForgotten69** [nesrak1/UABEA#285]
**Is your feature request related to a problem? Please describe.**

I think it will be great to batch edit/load textures from a directory if they have the exact same name as the asset mentioned.

**Describe the solution you'd like**

Being able to use a plugin to batch import exported textures from a directory and replace what the asset has.

**Additional context**

**Comment by nesrak1** [comment]
This is already supported. Filter by Texture2D, select all with ctrl+a, then plugins will have a batch import option.

**Comment by TheForgotten69** [comment]
Sorry I definitely had that missed.
