### ISSUE TITLE
Linux version does not open files without extension

### ISSUE THREAD

**Issue by xboxones1** [nesrak1/UABEA#288]
I'm using the latest nightly build, tested it on several distributions. The Linux version does not display files in explorer if they do not have an extension. For example, you cannot select the globalgamemanagers file, it simply does not exist. If you specify the extension, the file appears immediately. There is no such problem in the Windows version.

**Comment by nesrak1** [comment]
This is a bug in the Avalonia file picker.

**Comment by nesrak1** [comment]
I forgot to mention, but I believe dragging files into the window should work on linux.

**Comment by xboxones1** [comment]
This is another bug discovered, dragging file does not work on Linux

**Comment by nesrak1** [comment]
I misremembered. It's not a bug, just not implemented: https://github.com/AvaloniaUI/Avalonia/issues/6085

**Comment by nesrak1** [comment]
As for the original issue, it might be solved by turning all of the `*.*` filters into `*`, but I still believe this should behave the same on both OSes.

**Comment by xboxones1** [comment]
I build it with a modified filter and now it works as it should https://github.com/xboxones1/UABEA/commit/8cd9027acb1a50d11a2b397594ec9de48e6b824f

**Comment by xboxones1** [comment]
Thanks, it works now
