### ISSUE TITLE
Please support 2020.3.5f1c1

### ISSUE THREAD

**Issue by greenjerry** [nesrak1/UABEA#29]
I can’t load an assetbundle which starts with UnityFS and its version is 2020.3.5f1c1. It’s in the StreamingAssets folder. But I can load the other archives like “resources.assets”.

I can decompress it to a file which is about 2.8GB. But when I pressed "info" button, it was not responding and finally failed to open this archive.

Maybe the reason is that the version of the game is too new. 
Could you please update the UABEA to support new versions?
Thank you very much!

The assetbundle which I can’t open is here, about 780MB
https://drive.google.com/file/d/1FozQtomVLlVnFZLaTpT51uEFBiksrxSY/view?usp=sharing

The download link of the game is here, about 1GB
https://drive.google.com/file/d/1WxRhPoE7mcUOFaUdE-BQg_HwYSdMSO9l/view?usp=sharing

**Comment by nesrak1** [comment]
The issue was with the 2020.3 type database missing and crashing if it couldn't find it. I've added a type selection box, but some types may fail to load until it gets updated.
