### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by adel44y** [nesrak1/UABEA#290]
bro, I always support you to develop This tools ,I'm grateful. Can you update your tools to be able to read in the latest version 
![IMG_20231023_160926](https://github.com/nesrak1/UABEA/assets/148681422/07a09668-742c-446d-a7e5-da42a57de463)
![IMG_20231110_175847](https://github.com/nesrak1/UABEA/assets/148681422/cb686025-4593-4560-9420-fe6500a5f66a)
This is an example of an asset, is there a way to edit it? file.io/f92V1nYFEsPv

**Comment by nesrak1** [comment]
The picture you took with your phone is UABE, not UABEA. Additionally, this seems like the old 2.2 version.
