### ISSUE TITLE
Lethal Company (PC) - extract and import text not working properly

### ISSUE THREAD

**Issue by bartlomiejduda** [nesrak1/UABEA#291]
**Describe the bug**
I've tried to export text from game "Lethal Company". First I've searched for the text "**The autopilot will now attempt to fly to the closest safe spaceport**". I've found it in "level3" file. When I've opened this file in UABEA and tried to extract all assets from it, I've got some errors (screenshot attached). I'm attaching "level3" file and log file to this report.

[level3.zip](https://github.com/nesrak1/UABEA/files/13365283/level3.zip)

[uabeacrash.log](https://github.com/nesrak1/UABEA/files/13365297/uabeacrash.log)

**To Reproduce**
1. Launch UABEA
2. Go to File > Open
3. Select "Level 3 file"
4. Select all assets from the list with CTRL+A
5. Click "Export RAW"
6. See the error message. Program will crash at this point.

**Expected behavior**
Program should allow to export and import text from "level3" file.

**Screenshots**
![obraz](https://github.com/nesrak1/UABEA/assets/5502283/3f2d323f-21a4-43e1-8c63-668ee0545f17)

**Additional context**
None.

**Comment by nesrak1** [comment]
Did you click export raw and then select a folder? As the error suggests, the folder you're trying to export into does not exist (probably because you have a space after `PlayersManager`)

**Comment by bartlomiejduda** [comment]
Yes. I've created folder "**level3_out1**" and selected it for extraction. But I didn't create "Player Manager" folder (it's asset folder and it should be created automatically by the program) and I definitely haven't added any spaces to the path. So it's either error with the program or with the asset file itself. Please follow "reproduce steps" to see what I mean.

**Comment by nesrak1** [comment]
If you didn't add this, then I guess it's because an asset has a slash in the name. Apparently only export dump had name filtering. Now export raw has this.

**Comment by bartlomiejduda** [comment]
Thanks. It works now in the newest nightly build.
