### ISSUE TITLE
Error while exporting Texture2D in Unity 2023.2.3f1 version

### ISSUE THREAD

**Issue by LunarExpress** [nesrak1/UABEA#301]
Using the latest nightly build,an error occured while exporting Texture2d file.
This is the error report.
![Dingtalk_20240118143057](https://github.com/nesrak1/UABEA/assets/126585175/9ae889af-8cab-45b9-98db-a7c156434258)
Maybe the new version of unity changed save format of texture2d.I mentioned that when you exporting dump of Texture2d file,the text seems strange,not like earlier version.And the file offset is also not correct.
![2222](https://github.com/nesrak1/UABEA/assets/126585175/6acb854b-5f5d-4abb-a503-da6edb79655b)

**Comment by nesrak1** [comment]
Replace your classdata.tpk with the one in this zip: https://nightly.link/AssetRipper/Tpk/workflows/type_tree_tpk/master/lz4_file.zip

**Comment by LunarExpress** [comment]
> Replace your classdata.tpk with the one in this zip: https://nightly.link/AssetRipper/Tpk/workflows/type_tree_tpk/master/lz4_file.zip

That solves the problem,thank you
