### ISSUE TITLE
When importing a dump in txt format, the asset breaks

### ISSUE THREAD

**Issue by xboxones1** [nesrak1/UABEA#303]
When importing a dump in txt format, the asset breaks. After saving and re-exporting it says `Asset failed to deserialize.` Everything works with a dump in json format

**Comment by nesrak1** [comment]
Need more information to fix. What did you change (if anything)? What's in the file (any managed references)? What type is the asset? Anything you can give me is helpful.

**Comment by xboxones1** [comment]
Open globalgamemanagers - BuildSettings, export it to txt, you don’t even have to edit it, import it back and save it’s broken

**Comment by nesrak1** [comment]
Can you try replacing your classdata.tpk file with the tpk in this zip? https://nightly.link/AssetRipper/Tpk/workflows/type_tree_tpk/master/lz4_file.zip

**Comment by xboxones1** [comment]
Yes, now the import works correctly, the asset does not break. Thanks
