### ISSUE TITLE
Can't extract with the Unity 2022.3.17f1 version

### ISSUE THREAD

**Issue by muslimcyber26** [nesrak1/UABEA#306]
Can you please update to Unity Version 2022.3.17f1. Because I want to unpack the .bundle data, but I can't. And I got this error:

`This doesn't seem to be a valid assets file, although the asset is serialized. Maybe the file got corrupted or is too new of a version?`
![aaaa](https://github.com/nesrak1/UABEA/assets/17708101/16387639-3eef-414b-8b1a-2863f63a5304)

And I've included the bundle file for you to check out.
[000bec2562040acf7d4c7c69d822260b.bundle.zip](https://github.com/nesrak1/UABEA/files/14230271/000bec2562040acf7d4c7c69d822260b.bundle.zip)

**Comment by nesrak1** [comment]
File is encrypted so you're on your own.

**Comment by muslimcyber26** [comment]
Do you know any tools that can decrypt asset bundles?

**Comment by nesrak1** [comment]
I can't help, this is out of scope for UABEA. If you need to ask, you're out of luck.
