### ISSUE TITLE
Weird Unity's package format

### ISSUE THREAD

**Issue by Cosetto** [nesrak1/UABEA#307]
I wonder if you can check this package to see if it can be exported/imported, it's the smallest package from the game. [link](https://mega.nz/file/irwWyZ6Y#X-EFcEjHD1ITmx-t26Qiak-Lx1424JT3qq1ZPBQELqM)

This is the first time I see something like this:
![image](https://github.com/nesrak1/UABEA/assets/81801486/aa6c8783-d36d-42b8-88f0-a99b7acd2427)
Thanks in advance

**Comment by nesrak1** [comment]
This is probably a custom format so it's not really a UABEA issue, but it seems fairly easy to figure out with what seems to be a basic table of addresses and sizes and presumably the data following it.

**Comment by Cosetto** [comment]
Solved
