### ISSUE TITLE
Search by name not working and Plugin crash

### ISSUE THREAD

**Issue by DarklDrift** [nesrak1/UABEA#32]
Hi! I found two mayor issues with the program. First when i click on the Search by name button nothing happens. Second is the with the plugins button. When i click on the plugins button the UABEA stop working and then a crash.
SECOND RELEASE

**Comment by nesrak1** [comment]
> First when i click on the Search by name button nothing happens.

Searching is not implemented yet so it doesn't do anything right now.

> When i click on the plugins button the UABEA stop working and then a crash.

Can you please post a [stack trace](https://github.com/nesrak1/UABEA/issues/15#issuecomment-826471729)?

**Comment by nesrak1** [comment]
I need the .NET Runtime error, not the Application error.

**Comment by HyperSnip3r** [comment]
Nesrak1 Is it ok with you if I make a Youtube video showing how to make Among Us hats with your UABE ?

**Comment by nesrak1** [comment]
Yes

**Comment by DarklDrift** [comment]
yes

**Comment by nesrak1** [comment]
The error seems to suggest there was no asset selected, but try the [latest build](https://nightly.link/nesrak1/UABEA/workflows/dotnet-desktop/master/uabea-windows.zip) anyway to see what happens.

**Comment by nesrak1** [comment]
Can't reproduce the crash, so I'm closing this issue. Reopen this if you still have issues.
