### ISSUE TITLE
Unable to extract images in 2023.2.8f1

### ISSUE THREAD

**Issue by ye1088** [nesrak1/UABEA#320]
Unable to extract images in 2023.2.8f1

game url : https://apkpure.com/cn/survivor-z-loot-and-survive/com.EternalStudio.SurvivorZ

![image](https://github.com/nesrak1/UABEA/assets/16268284/b6a5e77a-f6f5-4716-aa13-777e343328b1)

![image](https://github.com/nesrak1/UABEA/assets/16268284/ecc7d544-eb3c-4c00-9623-084ba046cde3)

![image](https://github.com/nesrak1/UABEA/assets/16268284/fe3d5edb-517e-4869-86a2-ac5f14a3ae84)

**Comment by nesrak1** [comment]
Can you try replacing your classdata.tpk file with the tpk in this zip? https://nightly.link/AssetRipper/Tpk/workflows/type_tree_tpk/master/lz4_file.zip

**Comment by ye1088** [comment]
> Can you try replacing your classdata.tpk file with the tpk in this zip? https://nightly.link/AssetRipper/Tpk/workflows/type_tree_tpk/master/lz4_file.zip

It's useful, thank you
