### ISSUE TITLE
Can't save .png texture with Edit Texture plugin after game update [Dreamlight Valley]

### ISSUE THREAD

**Issue by MaximiliumM** [nesrak1/UABEA#329]
**Describe the bug**
After the game got an update, I can no longer edit Texture2D using the included plugin. Old .bundle files from the previous version still work fine. Unfortunately, I can't use old .bundle files with the new game patch, it crashes the game.

**To Reproduce**
1. Extract sample files.zip included below
2. Open the new.bundle with UABEA and select Memory
3. Open Info panel and select the first one: avatar_female_body_C_df
4. Open Plugins panel and select Edit texture
5. Select Load at the bottom and select the provided .png file
6. Press Save and see the error: Failed to encode texture format DXT3!

If you follow the same steps but instead of opening the new.bundle, you open the old.bundle, everything will work fine.

**Files**
[sample files.zip](https://github.com/nesrak1/UABEA/files/15183333/sample.files.zip)

**Comment by nesrak1** [comment]
Probably a tpk issue. I will update in when I make a release today. See here for how to upgrade it yourself: https://github.com/nesrak1/UABEA/issues/320#issuecomment-2017187399

**Comment by MaximiliumM** [comment]
> Probably a tpk issue. I will update it when I make a release today. See here for how to upgrade it yourself: [#320 (comment)](https://github.com/nesrak1/UABEA/issues/320#issuecomment-2017187399)

Thank you so much! That fixed the issue.
