### ISSUE TITLE
How to export loaded files as Unity project

### ISSUE THREAD

**Issue by LarsThePenguin** [nesrak1/UABEA#331]
I have been trying to export a APK, but I can't figure out how to export it as assets/a Unity project. There are no bugs or anything. I just want to know if there is some button I cannot find, or if there is some other software I should be using

Note: Lots of the software I have used (Except UABEA) has crashed (The software I have tried are: uTinyRipper, UABE, AssetRipper, and AssetStudio).

**Comment by nesrak1** [comment]
Exporting unity projects is not something UABEA will ever support. Report the issue to AssetRipper's github or discord if you haven't already.
