### ISSUE TITLE
Import/Export TextAssetto JSON in bulk

### ISSUE THREAD

**Issue by tqdungctuct** [nesrak1/UABEA#335]
**Is your feature request related to a problem? Please describe.**
I’m translating a Visual Novel using the Unity Engine. I can use UABEA to find Text Assets and export dumps to JSON. However, I have to do it one by one because there are many files separately, not in a bundle. Is there any way to export/import TextAssets to JSON in bulk? I tried to use the command line, but it only exports to *.asset. Here is the example file structure:
https://drive.google.com/drive/folders/1wjdYS4Y4RkcLWiiY5y8z5p3-Y_pL9jyd?usp=sharing

**Comment by nesrak1** [comment]
Multi-bundle support is coming with UABEANext if that's what you're asking.
