### ISSUE TITLE
Command line doesn't work

### ISSUE THREAD

**Issue by DimaBilan** [nesrak1/UABEA#34]
Hello. In the second version, you added a command line but nothing happens when you enter these commands.

C:\uabea_rel2_win_x64\UABEAvalonia.exe -kd batchexport C:\uabea_rel2_win_x64\test.bat
C:\uabea_rel2_win_x64\UABEAvalonia.exe -fd batchexport C:\uabea_rel2_win_x64\test.bat

In the file test.bat itself indicated the path to the folder with the files .bundle "+DIR C:/uabea_rel2_win_x64/bundles/"

Sorry if this hasn't been implemented yet and I'm asking too much. It's just that I have a lot of compressed bundles to decompressed into .decomp files and it's impossible to do it all manually.

**Comment by nesrak1** [comment]
You'll need to make batchexport the first argument, then flags can come afterwards, like this:
`uabeavalonia batchexport -kd batch.txt`

Also there was a bug where the first argument was ignored in batchexport/import, so try the fixes from the [latest build](https://nightly.link/nesrak1/UABEA/workflows/dotnet-desktop/master/uabea-windows.zip).

**Comment by DimaBilan** [comment]
I downloaded the latest build and did as you said and it worked. Thank you very much.
