### ISSUE TITLE
Why folders with different languages ​​if you can’t change the program language?

### ISSUE THREAD

**Issue by TrueGodOfHyperdeath** [nesrak1/UABEA#343]
Hello. I wanted to change the program language to Russian, since there is a folder "ru". I haven't found how to do this. If the program language is English, then why are there these folders with different languages?

![image](https://github.com/nesrak1/UABEA/assets/96071214/c4ee720e-1012-4fc3-860b-9e2e1c0b10f5)

**Comment by nesrak1** [comment]
There is no translation other than English. Avalonia (the UI framework) puts those there, not me.

**Comment by TrueGodOfHyperdeath** [comment]
> Никакого перевода, кроме английского, нет. Авалония (фреймворк пользовательского интерфейса) помещает их туда, а не я.

понял, спасибо

**Comment by TrueGodOfHyperdeath** [comment]
> There is no translation other than English. Avalonia (the UI framework) puts those there, not me.

thank
