### ISSUE TITLE
Asset failed to deserialize.

### ISSUE THREAD

**Issue by pipiripapu** [nesrak1/UABEA#344]
Hello, I have tried to modify this subway surfers asset with another asset from its Chinese version by exporting and importing the meshes as dump (the same with animation clip), it has worked with other assets but not with this one, the asset fails to deserialize, there is any way to make it work? I also attach the assets
![1](https://github.com/nesrak1/UABEA/assets/170851499/8d867395-cae2-427b-bb19-cf99c9d20461)
[assets.zip](https://github.com/nesrak1/UABEA/files/15446629/assets.zip)

**Comment by nesrak1** [comment]
It seems like you imported the mesh asset from somewhere else. Asset dumps are not and will not be compatible between engine versions.

**Comment by pipiripapu** [comment]
so there is no way to replace?

**Comment by pipiripapu** [comment]
Hello, I solved it by using an asset but from the same Chinese version and using it in the global version
