### ISSUE TITLE
Program crash (resources.assets in the game "HuniePop").

### ISSUE THREAD

**Issue by Blasterhead** [nesrak1/UABEA#345]
I was just checking what can be opened/viewed by the program.

I tried to open "resources.assets" (Weight 433MB, Unity version, if I understood correctly "4.2.2") in the game "HuniePop", the program crashed.

[uabeacrash.log](https://github.com/nesrak1/UABEA/files/15459371/uabeacrash.log)

**Comment by nesrak1** [comment]
Games before Unity 5 are not supported.
