### ISSUE TITLE
Ability to Specify Unity Version if Stripped

### ISSUE THREAD

**Issue by vivific** [nesrak1/UABEA#346]
Hello! I've seen this issue addressed in #324 and related posts, but I was wondering if I could formally request re-adding support for specifying stripped Unity versions in order to use plugins.

I would like to make a guide for modding a game with stripped files (starting with texture mods, which necessitates the "Edit Texture" plugin) and the thought of having to walk everyone through personally compiling the program seems a bit daunting.

Thank you for your work on this program!

**Comment by nesrak1** [comment]
I whipped up something real quick. Hopefully it works for you, but I don't have any stripped bundles to test on so let me know if it works or doesn't.
