### ISSUE TITLE
replace scripts?

### ISSUE THREAD

**Issue by hgamingyt** [nesrak1/UABEA#352]
was wondering if theres any way to replace scripts? im trying to replace a script on a newer build of a game with the same script on a older build of the game

**Comment by nesrak1** [comment]
Replacing scripts is not something UABEA does. If possible, please use a mod loader which is made for this.

**Comment by Sidiusz** [comment]
I'm sorry for nectoposting, but what is the "mod loader"?

**Comment by nesrak1** [comment]
@Sidiusz not "the" mod loader but "a" mod loader. The popular mod loaders are MelonLoader and BepInEx, depending on your game.

**Comment by Sidiusz** [comment]
> @Sidiusz not "the" mod loader but "a" mod loader. The popular mod loaders are MelonLoader and BepInEx, depending on your game.

Ah, got it, thanks!
