### ISSUE TITLE
Bitdefender flagged this as malicious 

### ISSUE THREAD

**Issue by IzashiLavender** [nesrak1/UABEA#354]
I was using UABEA until Bitdefender deleted the exe file and flagged it as malicious. What's going on?

**Comment by guitutilo** [comment]
My bitdefender also shows that it is a virus, please fix it soon.

**Comment by nesrak1** [comment]
The release and nightly binaries are both compiled directly from the code. Feel free to browse around if you have doubts there are no viruses. Also feel free to report a false positive to bitdefender or add a local exclusion. There's not really anything I can do further on this.
