### ISSUE TITLE
Is it possible to export and import mesh with UABEA?

### ISSUE THREAD

**Issue by IVENEND** [nesrak1/UABEA#357]
3D model (mesh) modding for Unity3D games is always what I want. May I ask is it possible to export and import mesh with UABEA?

**Comment by nesrak1** [comment]
No, there's no feature for that right now. I'll eventually get to something like that, but as I get this question about once every other month, I'm going to close this issue.

https://github.com/users/nesrak1/projects/1?pane=issue&itemId=20027972
