### ISSUE TITLE
This doesn't seem to be an assets file or bundle. isssue

### ISSUE THREAD

**Issue by majeedjani** [nesrak1/UABEA#359]
after update game i am not able change game texture can you hlep know this message (This doesn't seem to be an assets file or bundle. ) 

please fix this issue 
![Screenshot 2024-07-23 201446ss](https://github.com/user-attachments/assets/fb4f6739-62a7-4ff9-a140-b5eb8ff3f826)
![Screenshot 2024-07-23 201728](https://github.com/user-attachments/assets/32558e41-f302-420b-9b1e-7d792a096849)

**Comment by nesrak1** [comment]
Real .assets files don't have that kind of naming. If it was a bundle, it might be encrypted. When it says it's not valid, it's generally right. I expect no other tool will open this either.

**Comment by majeedjani** [comment]
any other way to decrypt file than open file

**Comment by nesrak1** [comment]
If you have to ask, the answer is no
