### ISSUE TITLE
help!Unable to batch importing textures

### ISSUE THREAD

**Issue by tzhi4** [nesrak1/UABEA#364]
When I use the batch import function, there are no files in the window. Can you help me?
Can it recognize PNG files?
![屏幕截图 2024-07-31 043631](https://github.com/user-attachments/assets/3f70f25b-2eae-4a6e-a997-419aa9609065)

**Comment by 1103945342** [comment]
For batch import to take effect, you need to name the images according to the UABEA export image naming convention. You can refer to the naming format of batch exported images。
