### ISSUE TITLE
Multi-file export not working on Ubuntu

### ISSUE THREAD

**Issue by buerviper** [nesrak1/UABEA#367]
**Describe the bug**
When I want to export multiple assets, I have no actual option to do so.

OS: Ubuntu 20.04.6 LTS

**To Reproduce**
1. Open the .bundle file
2. Select "Info"
3. Select multiple files (either via CRTL+A or clicking on them with SHIFT or CTRL)
4. Select "Export Dump" (or any of the other export options, it does not make a difference)
5.  I can browse through my folders, but the "Open" button is constantly greyed out, even when I selected an empty folder. Actually, there is no "Choose folder" option at all. 
6. The only way to get out of this window is by selecting any file, after which the window closes, but nothing has been exported.

**Expected behavior**
When I choose a folder, it should export everything to the selected folder.

Single-asset export is working as intended.

**Additional context**
This bug also applies to UABEANext.

**Comment by nesrak1** [comment]
What desktop environment is this? Can you screenshot what the dialog box looks like? I doubt it's anything I can fix in this project and will have to be reported in Avalonia.

**Comment by buerviper** [comment]
It's Gnome, sorry for not mentioning.

This is what it looks like (excuse the German/English mix).
![uabea](https://github.com/user-attachments/assets/174d890b-6b4e-49a1-9912-f2e8dfe634e3)

**Comment by nesrak1** [comment]
I'll set up a gnome DE and see if I can reproduce.

**Comment by nesrak1** [comment]
My normal linux machine is kde, but I had gnome-like stuff on wsl2 (ubuntu 20.04) so I used that. The dialog box showed the select folder button ok:

![msrdc_8lRBCd9Cql](https://github.com/user-attachments/assets/11d37da3-fa1b-41ed-b160-1c34ae527773)

I asked a different friend who was also on gnome and he didn't have any issues either. Similar to #368 (which somehow by coincidence was posted on the same day), I don't see anything wrong with the code that opens folders and can't reproduce. Might be a system thing. Can you confirm if any other programs with open folder pickers work for you?

**Comment by buerviper** [comment]
Other programs work fine, there, the "Select File" button on top right switches to "Select" (or something similar - sorry, German system).

But I agree, it seems to be a machine-specific thing on my side. I will experiment a bit, because it definitely acts funky. Just now, randomly, the button actually changed to "Select" instead of "Open", but I cannot reproduce it at all (whenever I try now again, it's again "Open"). I don't know what caused this now, though.

**Comment by buerviper** [comment]
SO got it to work, eh, somehow. Basically, I upgraded to Ubuntu 22 and then ran the program with sudo and... it works. Before, it did not work with sudo (even though I believe the one time it actually changed to "Select" was with sudo, but I could not reproduce it).
