### ISSUE TITLE
UABEA breaks bundle, game doesn't start

### ISSUE THREAD

**Issue by Asharcky** [nesrak1/UABEA#375]
Importing a bundle file into UABEA will cause it to not be recognised by the game. In this case The Murder Of Sonic the Hedgehog.

1. Download TMOSTH
2. Open The Murder of Sonic The Hedgehog\The Murder of Sonic The Hedgehog_Data\StreamingAssets\aa\StandaloneWindows64\defaultgroup_assets_all_3a3b6c1fd8dd35a5213740db9e4c849e.bundle in UABEA.
3. Press Info.
4. Go to anything, press edit data, don't change anything, then press ok (just so it thinks we made a change and will save over the original bundle).
5. Press save and exit asset info
6. Save bundle (double check in the game's files that it has 100% saved a new file, sometimes I notice the time of the bundle is old and it did not rewrite the bundle)
7. Boot up TMOSTH, try starting a new game, expect to not be able to

 I was originally trying to replace the texture "sactx-0-512x1024-BC7-NamelessMC-ed05b1f1" in "defaultgroup_assets_all_3a3b6c1fd8dd35a5213740db9e4c849e.bundle", however when I did that and went to boot the game, I could not pass the title screen, pressing new game did nothing nor did load game. After some testing I figured out this happens even if you do not edit the Bundle, all you have to do is have the file run through the program. The same behaviour happens if you just fully delete the bundle, so presumably the game is not recognising the bundle at all.

If you do wish to try and test replacing the sprites texture, this is what I was trying to put in
![sactx-0-512x1024-BC7-NamelessMC-ed05b1f1](https://github.com/user-attachments/assets/2b175d12-cbb9-44c6-8e53-34a781b0bdb3)

**Comment by nesrak1** [comment]
That looks like an addressables bundle name.
https://github.com/nesrak1/UABEA?tab=readme-ov-file#addressables

**Comment by Asharcky** [comment]
yea u right, bless. thankyou i should have asked way sooner instead of messing around for hours lmao.
