### ISSUE TITLE
Unity 2022

### ISSUE THREAD

**Issue by TheCookiss** [nesrak1/UABEA#377]
The program cannot work with Unity 2022. It gives various errors and does not work properly. please fix it

**Comment by nesrak1** [comment]
> Cannot work on Unity 2022

It does support Unity 2022.

> It gives various errors and does not work properly.

I'd love to know what those various errors are and what "does not work properly" means.

**Comment by TheCookiss** [comment]
![изображение](https://github.com/user-attachments/assets/0b4e2749-ed36-4e01-a158-781a6cf6dcd5)
After working with unity 2022, all files receive an array error

**Comment by nesrak1** [comment]
It says it right there in the error: this is asset studio, not uabea
