### ISSUE TITLE
Please support textasset plugin

### ISSUE THREAD

**Issue by quicklyme** [nesrak1/UABEA#38]
Please support textasset plugin. It is unavailable now.

Or is there an alternative way to realize the function?

**Comment by Igor55x** [comment]
> Please support textasset plugin. It is unavailable now.
> 
> Or is there an alternative way to realize the function?

I can do that, follow this [link](https://github.com/Igor55x/UAAE).

**Comment by nesrak1** [comment]
You could always use import/export dump for now if you don't mind replacing \n newlines. But I'll add this when I get the time, it's pretty well requested.

**Comment by nesrak1** [comment]
Latest build should have textasset import/export support now.
