### ISSUE TITLE
Cannot extract any type of file

### ISSUE THREAD

**Issue by moemoee** [nesrak1/UABEA#387]
the game is https://vndb.org/v53137  I cannot extract any type of file from it.  please help
![QQ图片20241031211733](https://github.com/user-attachments/assets/a23beef6-f231-4889-83de-3232f3a10bb5)

[resources.zip](https://github.com/user-attachments/files/17588274/resources.zip)

**Comment by moemoee** [comment]
Just to add, I can export the original. dat file, but I cannot edit it. I would like to export a editable txt or json file
![QQ图片20241101131403](https://github.com/user-attachments/assets/c816352e-8abe-4719-bc68-c28eacd27fe7)
this is .dat file 
[AdvProject.book-sharedassets0.assets-245.zip](https://github.com/user-attachments/files/17596293/AdvProject.book-sharedassets0.assets-245.zip)

**Comment by nesrak1** [comment]
You will get this message when the dlls used for MonoBehaviour extraction aren't found. They are found in the Managed folder for managed games and other folders for il2cpp, depending on the platform. If you expand the error dialog, I believe it should show where it's looking.
