### ISSUE TITLE
MonoBehaviour files are incomplete

### ISSUE THREAD

**Issue by Yukikaze6512** [nesrak1/UABEA#390]
**Describe the bug**
The contents in the MonoBehaviour file is incomplete, with only the top section like the one below being available, while the rest of the contents is missing. I have tried to view it using AssetStudio and it is shown there.

`
0 MonoBehaviour Base
 0 PPtr<GameObject> m_GameObject
  0 int m_FileID = 0
  0 SInt64 m_PathID = 0
 1 UInt8 m_Enabled = 1
 0 PPtr<MonoScript> m_Script
  0 int m_FileID = 1
  0 SInt64 m_PathID = 1983
 1 string m_Name = "TitleDataBase"
`

I have put a DummyDLL folder from il2cpp dumper in the Managed folder of the game and disabled cpp2il in UABEA. It doesn't show any error but the file is incomplete.

**Comment by nesrak1** [comment]
Based on what you've told me, it's possible the mono script didn't load. What happens if you expand the m_Script PPtr in the view data dialog? Does it show up as [null]? If so, that script may be in another bundle that isn't loaded.

**Comment by Yukikaze6512** [comment]
I just tested this out, I believe this is indeed the case. The script is in another file named resources.resource, but UABEA doesn't seem to be able to open that one. Is there any way that I could modify the MonoBehaviour file in this case?

**Comment by nesrak1** [comment]
`.resource` files don't have asset data, they have audio data. The dependencies window (press F6 when a file is open) with the dropdown on the bottom set to the file you're looking at will map file ids to the serialized file it should be looking for. In this case, you're looking for `1 - somefilenamehere`

**Comment by Yukikaze6512** [comment]
I just double checked, actually I believe the mono script is in the same bundle. I tried again by loading only `resources.assets` into AssetStudio and it did show everything.

I have also tried adding all the dependency files to UABE but that didn't seem to work either.

![Screenshot 2024-11-20 125830](https://github.com/user-attachments/assets/42e87950-29eb-4809-9b4c-142c78e0c168)
![image](https://github.com/user-attachments/assets/c83102e4-48c0-4b77-9156-5b0993384844)

**Comment by nesrak1** [comment]
> I just double checked, actually I believe the mono script is in the same bundle.

File ID 1 tells us this _isn't_ in resources.assets (which is a serialized file, not a bundle fyi) but instead in globalgamemanagers.assets (a normal location for mono scripts).

Anyways, if uabea sees the monoscript (which it does in your screenshot), then whatever dependencies that are needed are loaded. The only other thing is looking for and loading the dlls. At this point, you should double check everything is correct. If the dlls were read but incorrectly, the dump would show an error. No fields indicates uabea did not find dlls and therefore did not do any extraction.

- Double check Managed is next to resources.assets (I assume the file you have open) and has the expected dlls
- Double check cpp2il is actually disabled
  - Make sure to reopen the file or restart uabea when this option is toggled. Monobehaviour information is cached, so it wouldn't fix until the next file open.

**Comment by Yukikaze6512** [comment]
I have checked globalgamemanager.assets, but I do not see the file I am looking for after opening it in UABE.

I have also checked that the managed folder is in the same directory and ensured that I disabled cpp2il and restarted UABE.

I apologize if my questions seem basic, as I'm still becoming familiar with Unity. Is it normal for the file to not appear, or will the name be different? Thanks in advance.

**Comment by nesrak1** [comment]
Monobehaviour extra fields only shows up if a dll at a path of (in our case) GameName_Data/Managed/Assembly-CSharp.dll exists AND cpp2il is disabled. You don't need to look at globalgamemanagers.assets. The fact that it's loaded is good enough, it's only necessary for uabea to read it but provides little useful information for anyone else.

**Comment by Yukikaze6512** [comment]
Thanks for the reply. Just to clarify, does this mean all I have to do is to add resources.assets and globalgamemanagers to UABE at the same time?

**Comment by nesrak1** [comment]
Again, if you open the monobehaviour and you can expand the m_Script pptr and it does not show [null] but instead shows [view data], the dependencies are loaded and you do _not_ need to manually load any other dependencies.

**Comment by Yukikaze6512** [comment]
Ah I have missed out on that part. My bad. It all works fine now. Thanks for the assistance!
