### ISSUE TITLE
The game stops seeing the repackaged bundle file.

### ISSUE THREAD

**Issue by wulf84** [nesrak1/UABEA#391]
If you make changes to the bundle file, the game stops seeing it, even if the changes are minor. How can this be fixed? The latest version of the program is used.
[localization-string-tables-english(en)_assets_all_orig.zip](https://github.com/user-attachments/files/17841338/localization-string-tables-english.en._assets_all_orig.zip)
[localization-string-tables-english(en)_assets_all_repackaged.zip](https://github.com/user-attachments/files/17841415/localization-string-tables-english.en._assets_all_repackaged.zip)

**Comment by nesrak1** [comment]
From the readme:

> Addressables
> Many games are also now using addressables. You can tell if the bundle you're opening is part of addressables because it has the path StreamingAssets/aa/XXX/something.bundle. [If you want to edit these bundles, you will need to clear the CRC checks with the CRC cleaning tool here](https://github.com/nesrak1/AddressablesTools/releases). Use Example patchcrc catalog.json, then move or rename the old catalog.json file and rename catalog.json.patched to catalog.json.

**Comment by wulf84** [comment]
Thank you, it worked. Good program, it would be cool to add “Create standalone .exe installer” in future versions.
