### ISSUE TITLE
Packaging issues

### ISSUE THREAD

**Issue by SVladimir20** [nesrak1/UABEA#395]
I want to change the text in the Turbo Overkill game files, which runs on Unity engine build: 2021.3.11. I found that the necessary ones are in the "**localization-string-tables-english(en)_assets_all.bundle**".
I downloaded the _latest version_ for work, and later downloaded the _unreleased 4th version_ that you have in the works.
The problem is that as soon as I resave the .bundle file, in the game itself, all the text breaks. I tried not changing anything at all - all the same. If I replace the original, everything is as it should be, that is, it's not somewhere in the game something breaks, it's just the way the modified file works. I tried using compression, but that didn't help either.

**Comment by nesrak1** [comment]
From the readme:

> Addressables
> Many games are also now using addressables. You can tell if the bundle you're opening is part of addressables because it has the path StreamingAssets/aa/XXX/something.bundle. [If you want to edit these bundles, you will need to clear the CRC checks with the CRC cleaning tool here](https://github.com/nesrak1/AddressablesTools/releases). Use Example patchcrc catalog.json, then move or rename the old catalog.json file and rename catalog.json.patched to catalog.json.

If that doesn't work, check your game's unity player log for more details.

**Comment by SVladimir20** [comment]
Yes, I realize the actions aren't complicated, but it was quite challenging for me to do. I did it, thank you very much.
Suggestion: could you add your program to UABEA Next, so that you can do it all more automatically?

**Comment by nesrak1** [comment]
Yes, I plan to as it's pretty much the # 1 question asked about uabea. But I don't have time to work on anything until next year.
