### ISSUE TITLE
It takes a very long time to open a file larger than 1 GB.

### ISSUE THREAD

**Issue by drongood12** [nesrak1/UABEA#40]
I tried to open a 3 GB file first, waited about 20 minutes, but the program did not open it, I also tried to open a 1 GB file and also waited about 20 minutes, the file still did not open

**Comment by nesrak1** [comment]
I need a little bit more info...
Did you open a bundle or an assets file?
If it is a bundle, are you opening by memory or file?
What version of unity is the game?

I've yet to see uabea take more than 5 seconds to open even 4gb bundles so obviously something else is going wrong.

**Comment by drongood12** [comment]
I tried bundle first, but it crashed immediately when I tried to open it, which is why I had to use UAAE, I took out a file from the bundle without extension, apparently it was an asset and after that I tried to open it already in UBEA, as a result, the program just froze. In UAAE and AssetStudio, the same file opens without problems, but they have a number of drawbacks that UAAE lacks, but it seems not all

**Comment by nesrak1** [comment]
If you're able to, can you send a file or tell me what game it is so I can see if it crashes for me?
Secondly, are you using the latest build or the second release?
I still don't have enough information right now other than that it's not working.

**Comment by drongood12** [comment]
1. Game - Rust
2. I am using the second release, now I will try to collect the current version from the sources
If you have this game, you can find the bundle in the game folder Bundles / shared / content.bundle
If you do not have this game, then you can generate these files as indicated on the wikia https://wiki.facepunch.com/rust/Creating-a-server
Personally, I did through the second method

**Comment by drongood12** [comment]
stack trace:
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Сообщение = Non-negative number required. Arg_ParamName_Name
  Источник = System.Private.CoreLib
  Трассировка стека:
   at System.IO.BinaryReader.ReadBytes(Int32 count)
   at AssetsTools.NET.AssetBundleFile.Unpack(AssetsFileReader reader, AssetsFileWriter writer)
   at UABEAvalonia.MainWindow.DecompressToMemory(BundleFileInstance bundleInst) in C:\Users\andrew\Documents\UABEA\UABEAvalonia\MainWindow.axaml.cs:line 498
   at UABEAvalonia.MainWindow.<MenuOpen_Click>d__25.MoveNext() in C:\Users\andrew\Documents\UABEA\UABEAvalonia\MainWindow.axaml.cs:line 144

**Comment by nesrak1** [comment]
Yep, getting the crash and it's because byte arrays in c# only support like 2gb or so. I thought I had updated AssetsTools.NET already to handle larger files but I guess not. I think the real issue is that memory streams are also limited by that size and will require a little bit of reworking with either writing temp files or writing directly into the decompressed file. But not really an issue with UABEA. I'll keep you posted.

**Comment by drongood12** [comment]
Wonderful, thank you

**Comment by nesrak1** [comment]
[Latest build](https://nightly.link/nesrak1/UABEA/actions/runs/889508088/uabea-windows.zip) opens content.bundle, let me know if it works for you.

**Comment by drongood12** [comment]
Yes, opening bundles is now working, thanks, I also hope for a quick fix of the problem with assets

**Comment by nesrak1** [comment]
Glad it works. I pushed changes to AssetsTools.NET to support compressed bundles so once that gets a new release, UABEA will be able to use it.
