### ISSUE TITLE
Saving large assets is very slow

### ISSUE THREAD

**Issue by drongood12** [nesrak1/UABEA#41]
Apparently this problem came from UABE, I tried to save a file of 1.1 GB in size and in about 20-30 minutes only 30% of the data (300 MB) was saved. I tried it in other similar programs, where I saved the entire file in two hours, here, as I understand it, the same problem awaits me

**Comment by drongood12** [comment]
![image](https://user-images.githubusercontent.com/73915636/120095140-f2227b80-c12c-11eb-9483-104acd3ffc60.png)
also observe a similar problem if I change the data by opening the gang and selecting the appropriate asset, after changing the data, I press save and my program hangs, I have been waiting for 10 minutes until it hangs, the file has a size of 3 GB

**Comment by nesrak1** [comment]
The slowness came from linq calls in assetstools so I've replaced them with dictionary lookups and it's much faster (about 30 seconds total, mainly limited by write speed at this point). The repo/build bot only uses the nuget releases for assetstools, so you'll need to build from source and replace the nuget version of assetstools with the latest commit from [github](https://github.com/nesrak1/AssetsTools.NET).

**Comment by drongood12** [comment]
Yes, it saves very quickly now, thanks!
