### ISSUE TITLE
request

### ISSUE THREAD

**Issue by GOALARG** [nesrak1/UABEA#44]
hi, amazing work , thanks!

can U  add version number to realeases UABEa? about Uabea, version! thanks again!

**Comment by nesrak1** [comment]
I don't know what you're asking. Are you saying I should make a newer release?

**Comment by GOALARG** [comment]
hi! no, I say if you can add program version, example, Uabea v1.01 or v1.01Beta2 ,

**Comment by nesrak1** [comment]
To the program or the releases page?

**Comment by GOALARG** [comment]
hi master, to the program =)

**Comment by kourain** [comment]
I can use it 
the program always ends automatically every time I open the assets file (UnityFS 5.x.x 2020.2.2f1)

**Comment by nesrak1** [comment]
@kourain this is a separate issue, please make a new issue for this.
