### ISSUE TITLE
MonoBehaviour export has no data.

### ISSUE THREAD

**Issue by mskgroup** [nesrak1/UABEA#45]
MonoBehaviour export has no data. For bundle and il2cpp formats, I have used il2cppdumper to export the .dll and put it in the Managed folder, but the exported MonoBehaviour still contains no data.

game: Popular City War_v0.9
Game file:[https://mega.nz/file/wNUHjQ4Y#FBUJBLAJRzKmX56K6maG0LSiEoTeOl2y5DlZVVFdn-I](url)

UABEA 32b8dd9

**Comment by nesrak1** [comment]
Fixed with latest commit
