### ISSUE TITLE
Replace Texture But Save Failed

### ISSUE THREAD

**Issue by dw317748627** [nesrak1/UABEA#46]
my assetbundle version is 2020.3.7f1,I use latest build to open assetbundle and choose  2020.2.2f1 version.I want to Replace logoWhite(PathID 50),I click Plugins and Load New PNG, I saved Assets info and save New assetbundle,but the new assetbundle as same as old old assetbundle.
my assetbundle download url:https://dw-1255901256.file.myqcloud.com/data.unity3d
thanks

**Comment by nesrak1** [comment]
Did you figure this out? Was it a problem on your end?

**Comment by dw317748627** [comment]
It's my fault. I got it
