### ISSUE TITLE
Edit Unity2020.2.2f1 hava a bug

### ISSUE THREAD

**Issue by Coinswang** [nesrak1/UABEA#49]
Edit Texture ->choose xx.png->Save  
then crash...
[file.zip](https://github.com/nesrak1/UABEA/files/6610342/file.zip)

**Comment by nesrak1** [comment]
If you try to export png instead of edit, it'll tell you that the format failed to decode, I just don't have that message on import. Unity crunch isn't supported, but you can change the texture format to something like RGBA32 before you click Ok and it should work fine for most platforms.

**Comment by Tactful** [comment]
I tried changing the texture format from DTXCrunch to RGBA32 using the Edit Texture plugin and saving, but when I go to export as png it still says it's DTXCrunch and when I edit the texture again, it didn't save.

**Comment by nesrak1** [comment]
If you mean using the edit texture plugin to change the format from crunch to rgba, you can't do that right now. Op made it sound like they already had a texture to import. In his case, you wouldn't have to decode the crunch texture.
In your case, you want to change the crunch data to rgba data which requires decoding the crunch texture.
Also, texture reencoding is not supported right now anyway, if you don't import a texture, it doesn't do anything.

**Comment by Tactful** [comment]
Thanks for the swift response. Do you know how I could learn how to decode to something viewable?

**Comment by nesrak1** [comment]
You could for the time being export with assetstudio then import back with rgba with this.

**Comment by Coinswang** [comment]
RGBA32 can work，thanks！

**Comment by Coinswang** [comment]
RGBA32 can save the file，but replace this in  game file ,game will crash...
logcat:
 
    pid: 12070, tid: 12128, name: UnityMain  >>> packagename <<<
    uid: 11634
    signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xb6ffa138
        r0  fffffe04  r1  b6ff9f3d  r2  00000000  r3  00800000
        r4  c67c30cc  r5  c4aab000  r6  00000000  r7  b6ff9f40
        r8  c4acb3d8  r9  b6ffa130  r10 00000e04  r11 c4f08a68
        ip  c4acb000  sp  c4f089f0  lr  b0c7c5a2  pc  c523c768
    
    backtrace:
          #00 pc 0032e768  /data/app/~~UhrpG1ixOwfqtoOYQon9KQ==/packagename -4x9xKgOmdafEdESBZ0Nqfg==/lib/arm/libil2cpp.so (BuildId: 4096121d6041cedfb8739a61d0ce22701ea2ae14)

**Comment by nesrak1** [comment]
Looks like m_CompleteImageSize wasn't being set so any imported textures of different size were failing to load. Fix coming soon.

**Comment by nesrak1** [comment]
Should be fixed in latest commits, let me know if it's working for you now
