### ISSUE TITLE
After importing the dumped Monob, the game cannot run

### ISSUE THREAD

**Issue by mskgroup** [nesrak1/UABEA#50]
After importing the dumped Monob, the game cannot run, even if I import it without modifying any data

game：IFSCL 4.1.X
Unity Ver：2019.2.21f1

错误应用程序名称: IFSCL41X.exe，版本: 2019.2.21.21133，时间戳: 0x5e38c4c5
错误模块名称: UnityPlayer.dll，版本: 2019.2.21.21133，时间戳: 0x5e38c65c
异常代码: 0x80000003
错误偏移量: 0x0000000000cebf44
错误进程 ID: 0x2cc0
错误应用程序启动时间: 0x01d75c06a4f9f675
错误应用程序路径: D:\Program Files\CodeLyokoGames\IFSCL 4.1.X\IFSCL41X.exe
错误模块路径: D:\Program Files\CodeLyokoGames\IFSCL 4.1.X\UnityPlayer.dll
报告 ID: 5401356a-e099-4ee7-8e54-48d16cd6996c
错误程序包全名: 
错误程序包相对应用程序 ID: 

故障存储段 1824718491076365433，类型 4
事件名称: APPCRASH
响应: 不可用
Cab ID: 0

问题签名:
P1: IFSCL41X.exe
P2: 2019.2.21.21133
P3: 5e38c4c5
P4: UnityPlayer.dll
P5: 2019.2.21.21133
P6: 5e38c65c
P7: 80000003
P8: 0000000000cebf44
P9: 
P10: 

附加文件:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB8C9.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB9D4.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB9F4.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBA02.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBA32.tmp.txt

可在此处获取这些文件:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_IFSCL41X.exe_d55fd96673ede1c54d3f4dc40c1f1ba2cb6d659_e83e8ac6_b29d7885-2bfb-4eda-8ef3-5063dee5ef31

分析符号: 
重新检查解决方案: 0
报告 ID: 5401356a-e099-4ee7-8e54-48d16cd6996c
报告状态: 268435456
哈希存储段: 1510267f62846a37e952b3ccc3b18c79nCab GUID: 0
[AppCrash_IFSCL41X.exe_d55fd96673ede1c54d3f4dc40c1f1ba2cb6d659_e83e8ac6_b29d7885-2bfb-4eda-8ef3-5063dee5ef31.zip]
(https://github.com/nesrak1/UABEA/files/6612898/AppCrash_IFSCL41X.exe_d55fd96673ede1c54d3f4dc40c1f1ba2cb6d659_e83e8ac6_b29d7885-2bfb-4eda-8ef3-5063dee5ef31.zip)

**Comment by mskgroup** [comment]
game download：https://ifscl.b-cdn.net/standalone/IFSCL_41X_Setup.exe

**Comment by nesrak1** [comment]
You didn't say which asset you tried, but my guess is you're editing a monobehaviour with an enum, and when importing it back in, it skips the field because it doesn't know what type it is (usually int). Will make fix later.

**Comment by mskgroup** [comment]
Yes it is monobehaviour
The following is an example file:

[Gunship IFSCL SDF Material-sharedassets0.assets-7.txt](https://github.com/nesrak1/UABEA/files/6613224/Gunship.IFSCL.SDF.Material-sharedassets0.assets-7.txt)
[TextColor_highlight-sharedassets0.assets-43.txt](https://github.com/nesrak1/UABEA/files/6613226/TextColor_highlight-sharedassets0.assets-43.txt)

**Comment by nesrak1** [comment]
>  0 ColorMode colorMode = 0

Definitely enums here, you can fix this temporarily by changing enums to int.

**Comment by mskgroup** [comment]
Okay, looking forward to this problem being fixed, thank you for everything

**Comment by dw317748627** [comment]
Year,I got it. thanks

**Comment by nesrak1** [comment]
This was fixed earlier today
