### ISSUE TITLE
i added asset,but i don't know how to use it.

### ISSUE THREAD

**Issue by dw317748627** [nesrak1/UABEA#53]
for example，i want to change button‘s image.but the button's image  is common asset.so i want create new image and the button use it

**Comment by mskgroup** [comment]
You can look for UABE tutorials, there should be many, UABE tutorials and UABEA are basically common

**Comment by dw317748627** [comment]
thasks,can you give me the web url

**Comment by mskgroup** [comment]
i think you can use google
