### ISSUE TITLE
Export dump and import dump monobehaviour ,after I repackage apk was crashed

### ISSUE THREAD

**Issue by dw317748627** [nesrak1/UABEA#54]
I export dump and import dump monobehaviour(don't change anything) and repackge apk, the game was crashed and logcat show error was level0 is corrupted! Remove it and launch unity again! But if I export raw and import raw(don't change anything) and rapackage apk,everything is ok.But i don't know how to Edit raw

**Comment by nesrak1** [comment]
#50
