### ISSUE TITLE
Export/Import as PNG/TGA

### ISSUE THREAD

**Issue by PipoCrazy** [nesrak1/UABEA#55]
Can we have two buttons for the Texture2D files in order to make the workflow faster? It is a nightmare to replace hundreds of textures with the current "Plugins/Edit Texture/Load". It would be much simpler to do that process with a button, choose a texture and then mess around with the Name, Format, etc. if needed.

Something as simple as this: https://i.ibb.co/jht1YyW/suggestion.png

PS: If there is a way to replace several textures at once please tell me how.

Thank you and keep up the excellent work.

**Comment by nesrak1** [comment]
You can batch import by selecting multiple assets (shift click) then clicking plugins. It looks for images with filenames from batch export however.

This is how it works in uabe, so I probably won't be changing it for now.

**Comment by PipoCrazy** [comment]
You have probably saved me 10+ hours of work. I shouldn´t have modified the texture names in my files, but it will be easy to rename them to their original names rather than importing all of them one by one each time the game updates.

Thank you very much and I hope that this project keeps growing up. I have found a lot of joy in modding Unity games.

Cheers!
