### ISSUE TITLE
Import Dump is not working

### ISSUE THREAD

**Issue by Chipsum** [nesrak1/UABEA#57]
Hi
I used to export the Font's SDF monobehavior with uabe and modify it then import it back
but with uabea it exports it incomplete (just about the fist few lines) and it doesn't import it at all (no modification occurs even that it displays the star * and save the file).

**Comment by nesrak1** [comment]
A few questions:
* Are you editing an assets file or a bundle file?
* When selecting the monobehaviour asset, does its fileid value show as 0 or something else?
* Is the game il2cpp? (Is there a managed folder with Assembly-CSharp.dll inside?)

**Comment by Chipsum** [comment]
- an asset file (resources.assets, sharedassets ...etc)
- yeah as 0
![image](https://user-images.githubusercontent.com/37517008/121566559-8a660d80-ca15-11eb-8089-9c24694d92ac.png)
- Yeah with assembly C# dll (dnspy thingy yeah)

**Comment by Chipsum** [comment]
But even with the latest update of the game (which uabe can open)
it's id is 0 but it does export it correctly and import it as well
![image](https://user-images.githubusercontent.com/37517008/121572541-34489880-ca1c-11eb-9a25-e551689ee47a.png)

**Comment by nesrak1** [comment]
Can't reproduce this bug on this asset on nightly. View data shows fine and export and import dump are working fine on 1.5.68.11808. For me though, I see the size of (Perpetua-SDF/sharedassets0.assets) as being 9132, not 11112

**Comment by Chipsum** [comment]
In fact I was wrong about the file, and yeah it's size is 9132
Closing till I find more about the issue.
I do remember that I exported a same Texture2D font and it gave me a black empty png instead of font's SDF letters.
I will be back after digging more about that.

**Comment by Chipsum** [comment]
I recall having the font's SDF in the previous update like that (a very long file specifying each unicode character)
![image](https://user-images.githubusercontent.com/37517008/121574759-81c60500-ca1e-11eb-962b-7b2853bfe146.png)
in uabea it's just the header info 
maybe the update changed a lot.

**Comment by nesrak1** [comment]
![image](https://user-images.githubusercontent.com/12544505/121575101-97bad200-c9ec-11eb-9946-9c1766cfa9a7.png)
This is what I get from uabea, I assume your screenshot is a 1.4 dump from uabe, but if you're not getting that then something's going wrong.

**Comment by Chipsum** [comment]
Yeah it was from 1.4
but in 1.5 (which the path id is 178 it does exactly the same as uabe when it doesn't find dlls to dump
in uabea it doesn't ask for it, so I don't know how is it finding it (but I assure you that it's in the correct order , I mean in managed folder)

**Comment by Chipsum** [comment]
In fact it's working I am so sorry for that, I did not pay attention to file names so stupid of me.
Thank you so much and excuse me not paying attention.
