### ISSUE TITLE
can't decode ETC_RGB4

### ISSUE THREAD

**Issue by Halal-Dev** [nesrak1/UABEA#59]
The game im trying to mod is granny chapter 3 by dvloper.
i get can't decode error when i try to export a texture2d and and i cant replace the texture.

**Comment by nesrak1** [comment]
Looks like I missed this format somehow, I'll add it soon.

**Comment by Halal-Dev** [comment]
Thank you

**Comment by nesrak1** [comment]
etc1 has been added

**Comment by Halal-Dev** [comment]
is it in the nightly build ?

**Comment by Halal-Dev** [comment]
or i have to build from source ?
