### ISSUE TITLE
Parse error when importing MonoBehaviour dump files

### ISSUE THREAD

**Issue by redhat-cat** [nesrak1/UABEA#6]
Hiya. When I try to import MonoBehaviour files using your tool, I get a 'Parse error' message saying that something went wrong when reading the dump file. It happens even when I try to import an unedited, freshly exported MonoBehaviour dump file.

**Comment by nesrak1** [comment]
Can you send me the file you tried to import?

**Comment by redhat-cat** [comment]
Here you go:
It's the original, unedited dump exported using your tool and I am unable to import it back in. Import feature works fine with smaller dumps.
[mono2.txt](https://github.com/nesrak1/UABEA/files/6313120/mono2.txt)

**Comment by nesrak1** [comment]
Looks like I forgot to escape newlines, I'll make a commit soon.
