### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by mskgroup** [nesrak1/UABEA#65]
Error C1047 The object or library file "E:\UABES\UABEA\TexToolWrap\crunch\win64\crnlib.lib" was created with a different compiler version from other objects (such as "obj\x64\Release\textoolwrap.obj") ; Please use the same compiler to regenerate all objects and libraries TexToolWrap E:\UABES\UABEA\TexToolWrap\LINK 1

**Comment by nesrak1** [comment]
Yes I'm aware already, but this commit was like two hours ago. Just be patient until the build test comes back green.

**Comment by mskgroup** [comment]
[win64.zip](https://github.com/nesrak1/UABEA/files/6705682/win64.zip)

I rebuild crnlib.lib for vs2019

**Comment by nesrak1** [comment]
It doesn't matter, it's apparently sensitive to minor compiler versions. I'll probably hack crunch into a dll.
