### ISSUE TITLE
Logging crashes?

### ISSUE THREAD

**Issue by JmTexas19** [nesrak1/UABEA#67]
Hi,

I was wondering if there was any sort of log file generated for crashes? Or if there was an easy way get the error message for crashes? Would the only way be to compile and run it myself in an IDE to troubleshoot?

I'm having a crashing issue compressing a file and wanted to see where the problem lies exactly.

Thanks

**Comment by nesrak1** [comment]
https://github.com/nesrak1/UABEA/wiki/Sending-a-crashlog shows where to find .net exceptions on windows.

**Comment by JmTexas19** [comment]
Great, didn't see that. Thanks
