### ISSUE TITLE
Edit Texture Plugin Error - Glitchy Graphics In-Game

### ISSUE THREAD

**Issue by ADuelGet** [nesrak1/UABEA#72]
Hello, I have been working on attempting to mod the newly released Wrestling Empire on Steam and while I am able to access and extract all of the texture files with ease, the issue I am having is when using UABEA to import textures.

When using the Edit Texture plugin, the PNG is inserted just fine and even looks as it should when exported again afterward. The problem however is that when the game is loaded up, these imported textures only show part of the texture at certain angles and the rest of the model is covered with garbled graphics (black with multi-color dots).

I have tested a number of things and I am certain that the issue is the plugin. Even when I import an untouched PNG from the original game into a different location in the file, it still has the same issue as if I edit and save a PNG in photoshop.

The only thing that I was able to point out that may be the cause of the issue is as follows:

- Similar files show a size of "204", imported images show a size much larger (e.g. 65652)
- When using Export Dump for pre-existing textures and imported textures, the imported texture has a massive number of items under Typeless Data, while the original game textures have zero items under Typeless Data.
- The imported textures have no data for the last few lines while original textures have numbers and a path.

Please see attached for examples of what I am referring to.

To be clear, I have very minimal experience using this program or modding this game, but having experience in troubleshooting, these were the few issues that I noticed that could have something to do with the issue as they are differences between the working and non-working textures.

Thank you!

[imported-texture.txt](https://github.com/nesrak1/UABEA/files/6758148/imported-texture.txt)
[original-texture.txt](https://github.com/nesrak1/UABEA/files/6758149/original-texture.txt)

**Comment by nesrak1** [comment]
> The only thing that I was able to point out that may be the cause of the issue is as follows:

This is by design to mimic what uabe does. Instead of storing texture data into the resS file, it stores it directly into the asset. This is normal.

> The problem however is that when the game is loaded up, these imported textures only show part of the texture at certain angles and the rest of the model is covered with garbled graphics (black with multi-color dots).

This could be a mipmap issue? Here's how you can check if that's it:
Open the original assets file and export dump the texture asset. Change m_MipCount to 1 and import the dump. Then edit the texture with the plugin like normal.

**Comment by ADuelGet** [comment]
Thanks for clarifying. I was actually wondering if it was a mipmap thing but I have limited knowledge of that. I will look at it and let you know how it goes tonight.

**Comment by ADuelGet** [comment]
That was it. I did the export and import like you said and changed the MipCount from 10 to 1 and then checked Has Mip Maps when importing the texture with the plugin and it showed up perfectly in-game.

Thanks again for the help!

**Comment by nesrak1** [comment]
Good to hear that was it. I can do this automatically, but I really should update the plugin to add mipmaps in the future.

**Comment by ADuelGet** [comment]
Thanks, yeah that would be more convenient. Now I just need to learn how to add a new texture entry into the file and how to decide the path ID to give it and such.

**Comment by nesrak1** [comment]
Forgot to mention but this bug has been fixed. You no longer need to manually set m_MipCount
