### ISSUE TITLE
Can't Open 2019.4.15f1

### ISSUE THREAD

**Issue by Hoa8888** [nesrak1/UABEA#76]
Hi,
I was downloaded your lastest build, but I can't open my asset file with header hex verison of UnityFS: 2019.4.15f1
Can you help me please ? :((

**Comment by nesrak1** [comment]
Can you send a file or tell me what game this is? I can't tell what the issue is just from a unity version.

**Comment by Hoa8888** [comment]
[1119_sunshangxiang_battle.zip](https://github.com/nesrak1/UABEA/files/6821360/1119_sunshangxiang_battle.zip)
Here is my file. Please check. Thanks

**Comment by nesrak1** [comment]
Non-standard header looks similar to #73, which might be encrypted.
