### ISSUE TITLE
plugins export BUG

### ISSUE THREAD

**Issue by Make1860** [nesrak1/UABEA#78]
If an error is reported during plugins export, the entire dump process will be interrupted. Can you modify it to skip the error report instead of interrupting the entire process?

**Comment by nesrak1** [comment]
Do you mean invalid texture format dialog in the texture plugin? I guess I can add a continue/cancel dialog but I'd rather fix the texture decoding error than add a workaround for it.

**Comment by Make1860** [comment]
UABE also has this problem, which cannot be avoided. It is more suitable to continue or cancel the problem at this stage. After all, it is simple, isn’t it?

**Comment by Make1860** [comment]
The problem of texture decoding error does exist, and it has little impact on me. The big impact is that the entire dump process is interrupted.

**Comment by Make1860** [comment]
The problem of texture decoding error does exist. It has little impact on me and can be handled. The big impact is that the entire dump process is interrupted

**Comment by nesrak1** [comment]
Would you prefer the errors to show up at the end of extraction in case there is more than one bad texture and don't want to have to keep closing error dialogs?

**Comment by Make1860** [comment]
unnecessary
It doesn't make sense to not show which file has an error
The current error is just a notification, he did not tell you where the error is, you need to find which file the error was reported by yourself, which is very troublesome

**Comment by Make1860** [comment]
In addition, the texture decoding error I mentioned means that after the texture is decoded, the picture is garbled, not an error.
Errors will directly interrupt the entire dump process

**Comment by nesrak1** [comment]
Latest build will now continue with errors and show first 20 errors at the end.
