### ISSUE TITLE
unity version 2019.4.5f1 modify file bug

### ISSUE THREAD

**Issue by spphinslove** [nesrak1/UABEA#79]
unity version 2019.4.5f1,can modify texture,but cant modify MonoBehaviour,once modify MonoBehaviour,the game will crash,and AssetStudio cant load the file after use UABEA modified.So I am sure there is a problem with "modify" function.

**Comment by spphinslove** [comment]
you can export dump Font_Default_JP and import without modify,and you cant open it with AssetStudio

**Comment by spphinslove** [comment]
file for test
https://mega.nz/file/Ca4lACCK#RQghyKOiSPSJV1lEkpPqS_bHln0getjVpAmqQXopqBg
https://mega.nz/file/GWwCTCLI#sZNpW2BVXDzLcu5GTQTr80SQvphB2onMo67ztG1o9bc

**Comment by nesrak1** [comment]
Is this asset a textmeshpro font? I just tested on a textmeshpro font by exporting and importing dump. It loaded correctly in assetstudio and the only difference was a `\\` didn't turn back into a `\`.
I assume since you were able to open a 2019.4 game you are using the latest build, correct?
Also when you export dump, is the file very large or just a few lines ending with m_Name?

**Comment by spphinslove** [comment]
> 
> 
> Is this asset a textmeshpro font? I just tested on a textmeshpro font by exporting and importing dump. It loaded correctly in assetstudio and the only difference was a `\\` didn't turn back into a `\`.
> I assume since you were able to open a 2019.4 game you are using the latest build of UABEA, correct?
> Also when you export dump, is the file very large or just a few lines ending with m_Name?

I export Font_Default_JP-resources.assets-29118 it a big file

**Comment by spphinslove** [comment]
can you import this modified file? and try  AS to priview or dump angin pathID 29118.AS told error "Array out support range"
https://mega.nz/file/DeIhWayA#5BGfBUP-7Z8X7YTecYu2ZvDnPmhH1aqsdlcgCheoYB4

**Comment by nesrak1** [comment]
These files do not have the same fields. You can just run a diff on the dumps:

game
```
    0 SInt64 m_PathID
 0 int m_AtlasTextureIndex
 1 bool m_IsMultiAtlasTexturesEnabled
 1 bool m_ClearDynamicDataOnBuild
 1 Array m_UsedGlyphRects (2670 items)
```

your dump
```
    0 SInt64 m_PathID
 0 int m_AtlasTextureIndex
 1 Array m_UsedGlyphRects (3970 items)
```

To fix the issue, just add these two fields in (or any more if you find any). There's no error checking on missing fields so you'll just have to make sure they match.

**Comment by spphinslove** [comment]
oh thank you,My bad.
