### ISSUE TITLE
pathID search bug

### ISSUE THREAD

**Issue by Make1860** [nesrak1/UABEA#80]
Thank you very much for your update. The new version is very helpful to me. I have found a new problem at present, please see if you have time to deal with it
1. During pathID search, can the file ID bring out 0-resources.assets by default, which can greatly improve efficiency
2. During path ID search, clicking cancel will cause the program to crash
3. After texture decoding, some textures are garbled, but they are much better than before
4.When searching pathID, can the OK button be bound to the Enter key?
If the above problems can be dealt with, for me, he will be a perfect substitute for UABE
Thanks again, thank for your help

**Comment by nesrak1** [comment]
1. done
2. fixed
3. what texture format? uabea should be using most of the same libraries that uabe uses, so the output _should_ be the same.
4. done

**Comment by Make1860** [comment]
All textures are in png format

**Comment by nesrak1** [comment]
The unity texture format (you can see the name in the texture edit plugin) not the file format you exported to (which is obviously png since that's the only file format you can export to)

**Comment by nesrak1** [comment]
Do the textures look the same in AssetStudio? RGBA32 for sure can't decode wrong, and I doubt the DXT5 implementation is wrong either.

**Comment by Make1860** [comment]
RGBA32 does have a decoding error. Searching in AssetStudio through pathID shows RGBA32

**Comment by nesrak1** [comment]
Can you answer the original question: Do the textures look broken in AssetStudio too or do they look correct?
If AssetStudio's textures look fine, can you export a dump of the Texture2D?

**Comment by Make1860** [comment]
The RGBA32 texture is displayed normally in AssetStudio, and it is also displayed normally through AssetStudio dump

**Comment by nesrak1** [comment]
Can you upload the dump from UABEA here?

**Comment by Make1860** [comment]
https://xiangfenglin.cn:5001/sharing/TpR0P9AGi
There is a detail, the texture decoding error starts from 7500 sheets

**Comment by nesrak1** [comment]
Sending me broken textures doesn't help me. I already know they are broken. Please select the texture2d in UABEA and click export dump and send the text file.

**Comment by Make1860** [comment]
https://xiangfenglin.cn:5001/sharing/CEzSmlAY3
From 7524 to 8617 (the last one), all decoding errors, before 7524 it was normal

**Comment by nesrak1** [comment]
Yes that dump works. The issue is as I expected in that the old resS offset size is 4 bytes but was recently changed to 8 bytes. This should be easily fixed.

**Comment by Make1860** [comment]
https://xiangfenglin.cn:5001/sharing/4w0lBP71F      Texture decoding normal dump file
The dump file with normal texture decoding looks the same as the abnormal file

**Comment by nesrak1** [comment]
Texture offset is now a long. I don't have any games with enough textures to test it, so let me know if it's still broken on latest build.

**Comment by Make1860** [comment]
The texture problem has been solved, and the previously wrong files can be dumped normally

**Comment by Make1860** [comment]
Excuse me, is there any way to export the absolute path of texture,Can you add such a function
