### ISSUE TITLE
Can UABEA open .bundle files?

### ISSUE THREAD

**Issue by TheSingleOneYT** [nesrak1/UABEA#81]
Can UABEA open .bundle files? (I can’t check at the moment)

**Comment by nesrak1** [comment]
Probably, but why don't you just try opening it?

**Comment by RamcesGD** [comment]
I mean i found a among us file that is a .bundle but i don't know how to save it as .bundle again i only just export it as .file but if i change it all to the same file name and .file name it seems not to load the maps

**Comment by TheSingleOneYT** [comment]
> Probably, but why don't you just try opening it?

I’m on holiday so I can’t check, someone asked in my comments on a video about UABEA

**Comment by nesrak1** [comment]
@RamcesGD are you saying you exported the assets files but didn't import them? if the .bundle file is an addressable, editing shouldn't be an issue.

**Comment by TheSingleOneYT** [comment]
You can open a .bundle file as long as you uncompress it.
