### ISSUE TITLE
Texture replacement gives a glitched texture

### ISSUE THREAD

**Issue by HeroRyker** [nesrak1/UABEA#84]
When I tried to change a 2d texture it glitched the texture out
(https://user-images.githubusercontent.com/88150222/127508138-2ce9d096-c40b-4091-bb40-1e0c6e83452e.jpeg)

**Comment by nesrak1** [comment]
Are you saying you imported a texture and immediately exported it and it made this image?
In the edit window, what texture format is it using?

**Comment by HeroRyker** [comment]
No I had a texture I used that texture to replace another texture but It ended up with that

**Comment by nesrak1** [comment]
But the image you posted above came from uabea right? Did you not:
1. import a png with edit texture
2. export texture to png (not jpeg like your extension shows)
3. upload png here

**Comment by HeroRyker** [comment]
I click the plugins tab while selecting a texture, clicked edit, clicked load texture, then I clicked my replacement texture, then hit ok. When I loaded up asset studio tocheck if it worked it showed a glitched texture. I opened in in UABEA exportd it, but still the same glitch texture

**Comment by nesrak1** [comment]
Can you tell me what texture format it is (not image format like png). You can find the texture format in the edit texture window in UABEA or the top left of the screen in AssetStudio.

**Comment by HeroRyker** [comment]
C17? i think

**Comment by nesrak1** [comment]
I know it's a bit late, but you may have had issues if the texture you tried to import did not have a width (or maybe height) divisible by 4.

**Comment by ezjax** [comment]
Hello, 
Kind of a Noob Using this program but the game I currently mod using this program, I Mod only 3d Landscape textures which are all DXT format. I am able to batch the Files I Mod into the assets file, but MIPS are not being Built, distant views are all blurry and have noise on camera movement, plus after batching when I check the view data dialog, all textures Mipcount Numbers have been change to 1. 

So is there special way to get the MIPS to build when importing, also tried importing 1 by 1 with no luck.

thks

**Comment by nesrak1** [comment]
Sorry, I don't have any mip map generation at the moment. For some formats it's pretty easy but other formats, it's breaking entirely. It's on the todo list though, you'll probably see some implementation of it in the next UABEA release.

**Comment by nesrak1** [comment]
If you need a solution _now_, I believe UnityPy semirecently added mipmap generation, and UABE if it supports the version you want.

**Comment by ezjax** [comment]
Ok thanks,
