### ISSUE TITLE
Sanitize filenames before attempting to write them during export

### ISSUE THREAD

**Issue by xperia64** [nesrak1/UABEA#88]
I have a Unity asset bundle where the author clearly fat-fingered a backslash into the name of a GameObject, and when bulk text-exporting multiple assets, the program will crash rather than sanitize the filename or skip the file.

I noticed there's no path sanitization in the codebase at the moment, so it may be a good idea to add this. I wouldn't be surprised if there are other asset bundles with similar invalid filenames as it seems Unity allows pretty much anything in the scene hierarchy.

I'd submit a PR myself, but I'm not really familiar with C# best practices for this sort of thing.

**Comment by nesrak1** [comment]
Good catch, didn't realize Unity let you do that. I have it filtering filenames with underscores. Let me know if it works for you.

**Comment by xperia64** [comment]
Yep, working fine now with the change from fcaab5eb1c504f483afff2dc858dada01a60c24a. Thanks!
