### ISSUE TITLE
Unable to compress file

### ISSUE THREAD

**Issue by ea965566** [nesrak1/UABEA#89]
![12](https://user-images.githubusercontent.com/78455261/129121691-511a4bb2-cefc-460d-ba6f-1d19b37887b9.png)

This button does not work, I need it

**Comment by ea965566** [comment]
![unknown](https://user-images.githubusercontent.com/78455261/129122270-719fe851-a745-4cb2-9d19-5d53bdcffdf4.png)


I need a compression method like this

**Comment by nesrak1** [comment]
By does not work do you mean it doesn't open anything? Are you using the latest build?

**Comment by ea965566** [comment]
I am using the latest version
But it can’t compress like UABE

**Comment by ea965566** [comment]
Yes, nothing happens when I click this button

**Comment by ea965566** [comment]
It succeeded, thank you very much
