### ISSUE TITLE
Importing dump does not work

### ISSUE THREAD

**Issue by phantasmx** [nesrak1/UABEA#9]
When trying to import dump, it does literally nothing. Tried to import freshly exported dump and edited dump. No indication in "Modified" column, no change when saving.
File -> Save from main window also does nothing, no saving dialog, no change in file.
Export dump and View data work fine.

Sample bundle (Unity 2019.4) https://workupload.com/file/WNkAbv43Qp3

Tried same on another game bundle (Unity 2018.4), same result.

**Comment by nesrak1** [comment]
I added import support for assets files but not bundle files (for some reason I forgot). I'm pushing a commit later to allow bundle saving. Also for the modified * thing, there seems to be a bug in Avalonia that makes this not show up initially. If you scroll the entry off the window and back on the window you should see the * appear.
