### ISSUE TITLE
Sprite/Game Issue

### ISSUE THREAD

**Issue by SrBeepo** [nesrak1/UABEA#90]
Is a there a plugin to modify sprites and replace them with custom made ones? Also whenever I try to replace a texture and reimport it into my game it causes it to crash whenever I run it.

**Comment by nesrak1** [comment]
The sprite plugin/tool is wip but I haven't had time lately to work on it.

As for the crash, do you mean an in-game crash or uabea crash? What unity version is the game? Is this a bundle or an assets file? What texture format does the edit dialog say? If you change the format to rgba32 does it no longer crash?

**Comment by SrBeepo** [comment]
It's an in-game crash.

The unity version of the game is 2019.4.15. It's an assets file and the texture format is RGBA32.

**Comment by nesrak1** [comment]
Can you post the error?

**Comment by SrBeepo** [comment]
![Capture](https://user-images.githubusercontent.com/88997263/129645206-3402c32c-e59e-4f4b-b511-29ebd82affaf.PNG)

The game crashes every time I try to go online.

**Comment by SrBeepo** [comment]
![Capture](https://user-images.githubusercontent.com/88997263/129701679-33c5b335-f540-4be4-a21c-042e78480385.PNG)

**Comment by nesrak1** [comment]
I can't reproduce this when editing a few textures in the game. Maybe paste your output_log.txt? Also, `the object you want to instantiate is null` sounds like a c# problem rather than an assets issue (otherwise the game would crash).

**Comment by SrBeepo** [comment]
Where do I find the file?

**Comment by nesrak1** [comment]
> ... I was editing the wrong file.
> It works now though.
