### ISSUE TITLE
Unable to launch application from Windows 10 start menu search

### ISSUE THREAD

**Issue by xperia64** [nesrak1/UABEA#91]
When launching UABEAvalonia.exe from the Windows 10 start menu search as follows:
![image](https://user-images.githubusercontent.com/1392608/129994070-80a2e544-2eb2-46f4-9894-fc662c451fdc.png)

the application throws this error:
![image](https://user-images.githubusercontent.com/1392608/129994114-9960fac3-a107-404a-ac6e-ee85153c96f6.png)

It's fine when launched from Windows explorer, but I've seen similar issues in other .NET projects in regards to current working directory.

**Comment by nesrak1** [comment]
Hmm okay, I can change it to check by the executable rather than the current directory. I use classic/open shell which doesn't have this issue, so I've never noticed.

**Comment by nesrak1** [comment]
Should be fixed now.

**Comment by xperia64** [comment]
yep, it works.
