### ISSUE TITLE
Crash when open file

### ISSUE THREAD

**Issue by trantrongle98** [nesrak1/UABEA#97]
The program stops unexpectedly when I open this file: [https://drive.google.com/file/d/1spCi4PVfO_rhzXOJh1ZeYI91RAdH21u_/view?usp=sharing](url) Please check it for me. Thanks.

**Comment by nesrak1** [comment]
https://github.com/nesrak1/UABEA/wiki/Sending-a-crashlog

**Comment by nesrak1** [comment]
Actually I think this is same game and issue as #96, #73, etc. This is a non-standard format that I don't know how to open.

**Comment by trantrongle98** [comment]
Can you support more version "Unity3d_2019.4.f15"? Please help me.

**Comment by trantrongle98** [comment]
You can support more version "Unity3d_2019.4.f15"? Please help me.

**Comment by nesrak1** [comment]
Since it looks encrypted or obfuscated in some way, there's no way I can figure this out without the game.

**Comment by trantrongle98** [comment]
Ahh, it is mobile game and this is link of game: https://m.apkpure.com/vn/garena-lien-quan-mobile/com.garena.game.kgvn/download. When you're free, you can check it out. Thank you.
