### ISSUE TITLE
Crunch Texture Replace Error.

### ISSUE THREAD

**Issue by louisome** [nesrak1/UABEA#98]
E/Unity: The texture could not be loaded because it has been encoded with an older version of Crunch. This can happen when loading AssetBundles containing Crunch-compressed textures built with Unity version prior to 2017.3 
    (Filename:  Line: 32)
 E/Unity: Failed to decompress Crunch texture data (size 512x512 format 65 mips 1) 
    (Filename:  Line: 747)

When I replace image which is "**ETC2_RGBA8Crunched**" format, it will show that log.

Unity Version 2019.4.28f1.

Thanks for your help.

**Comment by nesrak1** [comment]
Check latest build. I'm not entirely sure why this error happens though.
