### ISSUE TITLE
Opening assets when launching from the Windows 10 start menu crashes

### ISSUE THREAD

**Issue by xperia64** [nesrak1/UABEA#99]
Similar to #91, when opening an assets file when launched from the Windows 10 start menu, UABEA will crash because it cannot create the `plugins` directory.

This is because the working directory when launched from the start menu is `C:\Windows\System32` and is not writable.

**Comment by nesrak1** [comment]
Should be fixed as well. Hopefully that covers everything and I didn't forget about something else 🤦

**Comment by xperia64** [comment]
Yep, seems to work. Thanks!
